lynx-family/lynx-stack

README.md
packages/react/README.md
packages/rspeedy/core/README.md

Credits should be added for the SWC project, as it plays a significant role in powering `@lynx-js/react/transform`.

chore: add credits for the SWC project

---

.changeset/hip-stars-cross.md
packages/react/runtime/src/legacy-react-runtime/index.ts

We may split the compat logic (the runtime part and the transformer part) and release it separately in the future, when `@lynx-js/react-transform` can be refactored to a standard swc plugin.

fix(react): fix error `createRef is not a function`

---

.changeset/gentle-buses-ring.md
packages/react/transform/__test__/fixture.spec.js
packages/react/transform/index.d.ts
packages/react/transform/src/swc_plugin_compat/mod.rs
packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_compat/mod.rs/should_add_component_element_compiler_only.js
packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_compat/mod.rs/should_add_component_element_embedded_compiler_only.js

feat: add compiler only version of addComponentElement

---

.changeset/cuddly-papayas-start.md
packages/react/package.json
packages/rspeedy/core/package.json
packages/rspeedy/create-rspeedy/package.json
packages/rspeedy/plugin-qrcode/package.json
packages/rspeedy/plugin-react-alias/package.json
packages/rspeedy/plugin-react/package.json
packages/rspeedy/websocket/package.json
packages/third-party/tailwind-preset/package.json
packages/tools/css-serializer/package.json
packages/web-platform/web-constants/package.json
packages/web-platform/web-core/package.json
packages/web-platform/web-elements-compat/package.json
packages/web-platform/web-elements-reactive/package.json
packages/web-platform/web-elements/package.json
packages/web-platform/web-explorer/package.json
packages/web-platform/web-mainthread-apis/package.json
packages/web-platform/web-style-transformer/package.json
packages/web-platform/web-worker-rpc/package.json
packages/web-platform/web-worker-runtime/package.json
packages/webpack/chunk-loading-webpack-plugin/package.json
packages/webpack/css-extract-webpack-plugin/package.json
packages/webpack/react-refresh-webpack-plugin/package.json
packages/webpack/react-webpack-plugin/package.json
packages/webpack/runtime-wrapper-webpack-plugin/package.json
packages/webpack/template-webpack-plugin/package.json
packages/webpack/web-webpack-plugin/package.json
packages/webpack/webpack-dev-transport/package.json
packages/webpack/webpack-runtime-globals/package.json

Add `repository.url` for NPM provenance. See [CI failure](https://github.com/lynx-family/lynx-stack/actions/runs/13653835526/job/38168584888) for details.

chore: add `repository.url` for npm provenance

---

.github/workflows/deploy-main.yml

CI failed due to missing `GITHUB_TOKEN`.

ci: add `GITHUB_TOKEN` for canary publish

---

.changeset/tender-bikes-raise.md
packages/web-platform/web-constants/src/types/ElementOperation.ts
packages/web-platform/web-core/src/uiThread/decodeElementOperation.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/ElementThreadElement.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/createOffscreenDocument.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/elementCreating/elementCreatingFunctions.ts

refactor: add createOffscreenDocument and its createElement method

---

.changeset/dull-jokes-buy.md
packages/rspeedy/plugin-react/src/entry.ts
packages/rspeedy/plugin-react/src/splitChunks.ts
packages/rspeedy/plugin-react/test/config.test.ts

fix #63
- [x ] Tests updated (or not required).

fix(rspeedy/plugin-react): mkdir main:background fails in windows

---

.changeset/metal-jobs-hide.md
packages/rspeedy/plugin-react/src/entry.ts

fix(rspeedy/plugin-react): use path.posix.join for backgroundName to ensure consistent path separators across platforms

---

.changeset/modern-forks-unite.md
packages/web-platform/web-constants/src/constants.ts
packages/web-platform/web-core/src/utils/loadTemplate.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-tests/resources/web-core.main-thread.json
packages/web-platform/web-tests/tests/web-core.test.ts

https://github.com/lynx-family/lynx-stack/pull/90
This PR causes an issue:
the `registerDataProcessor` depending on the globalThis behavior.
Now we pass an updater callback to the runtime instance. This allows us to update the registerDataProcessor just like it's really assigned on globalthis.
```
var {ident} = runtimeInstance
runtimeInstance.updater = () => {
ident = runtimeInstance.storage.ident;
}
```
We just add a getter&setter for the "ident" value and call the updater on any new value set. This allows the DSL&User code to do this.
```
globalThis.ident = () => {};
ident();
```
Overall, the running code will work like this.
```
function entry(runtimeInstance) {
var {ident} = runtimeInstance;
runtimeInstance.updater = () => {
ident = runtimeInstance.storage.ident;
}
globalThis.ident = …
```

fix: some valus should be updateable by global scope

---

.changeset/calm-bees-roll.md
packages/web-platform/web-core/src/uiThread/bootWorkers.ts
packages/web-platform/web-tests/tests/react/api-SystemInfo/index.jsx
packages/web-platform/web-worker-runtime/src/index.ts

feat(web): add pixelRatio of SystemInfo, now you can use `SystemInfo.pixelRatio`.
- [] Documentation updated (or not required).

feat(web): add pixelRatio of SystemInfo

---

.changeset/fast-forks-build.md
packages/web-platform/web-core/src/apis/LynxView.ts

- Extract resize observer cleanup into a separate method
- Ensure proper disconnection and clearing of resize observer
- Add type safety to nativeModulesCall callback

refactor(web-core): improve LynxView resize observer cleanup

---

.changeset/odd-clowns-hide.md
packages/react/runtime/__test__/lynx/processEvalResult.test.js
packages/react/runtime/src/lynx.ts

Fix an error when using lazy bundle without main-thread-script(MTS).
This may happen when:
1. Using lazy compilation. See #7 
2. Using `import()` in [background-only code](https://lynxjs.org/react/thinking-in-reactlynx.html)

fix(react/runtime): use lazy bundle without MTS

---

.changeset/little-candles-brake.md
.changeset/violet-shoes-love.md
packages/rspeedy/plugin-react/src/entry.ts
packages/webpack/react-webpack-plugin/etc/react-webpack-plugin.api.md
packages/webpack/react-webpack-plugin/src/ReactWebpackPlugin.ts
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-lazy-bundle-production/bar.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-lazy-bundle-production/baz.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-lazy-bundle-production/foo.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-lazy-bundle-production/index.jsx
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-lazy-bundle-production/rspack.config.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-lazy-bundle-production/test.config.cjs
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-production/bar.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-production/baz.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-production/foo.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-production/index.jsx
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-production/rspack.config.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/amd-runtime-production/test.config.cjs
packages/webpack/react-webpack-plugin/test/create-react-config.js
packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts

When building a lazy bundle in a standalone project, we need the IIFE wrapper to inject `globDynamicComponentEntry`. But we also have a `var globDynamicComponentEntry` statement injected, which is not correct after minification.
```js
function (globDynamicComponentEntry) {
var globDynamicComponentEntry = globDynamicComponentEntry || '__Card__';
// ...
const __snapshot_xx = createSnapshot(globDynamicComponentEntry)
}
```
is minified to:
```js
function (globDynamicComponentEntry) {
var e = e || '__Card__';
// ...
var x = c(e)
}
```
which result in getting **WRONG** `entryName` in lazy bundle on the main-thread.
We just remove the `var globDynamicComponentEntry` when building standalone lazy bundle so that the output would become:
```js
function (globDynamicComponentEntry) {
// ...
var x = …
```

fix(webpack/react): `globDynamicComponentEntry` not found

---

.changeset/twenty-lamps-sort.md
packages/rspeedy/plugin-react/src/entry.ts
packages/rspeedy/plugin-react/test/config.test.ts

Use `.rspeedy/[name]/main-thread.js` instead of `.rspeedy/[name]__main-thread/main-thread.js`.
This is a regression of #76.

fix(rspeedy/react): use better name for `main-thread.js`

---

.changeset/tangy-pugs-peel.md
packages/react/runtime/__test__/snapshot/gesture.test.jsx
packages/react/runtime/src/gesture/processGesture.ts
packages/react/runtime/src/gesture/types.ts

Gesture may have configs like `minDistance` fro `PanGesture`, but it is not correctly processed. Now we add it when processing gesture object.

fix: gesture config not being processed correctly

---

.changeset/ready-numbers-type.md
packages/rspeedy/core/package.json
pnpm-lock.yaml

See: https://github.com/web-infra-dev/rsdoctor/pull/808

fix(deps): bump Rsdoctor v1.0.0-rc.0

---

.changeset/thirty-buses-exist.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/rsbuild/index.ts
packages/rspeedy/core/src/config/server/index.ts
packages/rspeedy/core/src/plugins/dev.plugin.ts
packages/rspeedy/core/test/config/server.test-d.ts
packages/rspeedy/core/test/config/validate.test.ts
packages/rspeedy/core/test/plugins/dev.plugin.test.ts

feat(rspeedy): support server.base

---

.changeset/forty-cobras-think.md
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-tests/shell-project/rpc-test/endpoints.ts
packages/web-platform/web-tests/shell-project/rpc-test/index.ts
packages/web-platform/web-tests/shell-project/rpc-test/worker.ts
packages/web-platform/web-tests/shell-project/web-core.ts
packages/web-platform/web-tests/tests/rpc.spec.ts
packages/web-platform/web-worker-rpc/src/Rpc.ts
packages/web-platform/web-worker-rpc/src/RpcEndpoint.ts

feat: `createRpcEndpoint` adds a new parameter: `hasReturnTransfer`.
When `isSync`: false, `hasReturn`: true, you can add `transfer` to the callback postMessage created.
At this time, the return value structure of register-handler is changed: `{ data: unknown; transfer: Transferable[]; } | Promise<{ data: unknown; transfer: Transferable[];}>`.

feat(web):  `createRpcEndpoint` adds a new parameter: `hasReturnTransfer`.

---

.changeset/mean-frogs-shop.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/mergeRspeedyConfig.ts
packages/rspeedy/core/src/index.ts
packages/rspeedy/core/test/config/mergeRspeedyConfig.test.ts

Implement a `mergeRspeedyConfig` method for merging Rspeedy configurations.
> [!NOTE]
> Please note that this is actually just an alias of [`mergeRsbuildConfig`](https://rsbuild.dev/api/javascript-api/core#mergersbuildconfig)

feat(rspeedy/core): add `mergeRspeedyConfig`

---

.changeset/soft-dragons-show.md
.changeset/warm-lamps-spend.md
packages/web-platform/web-constants/src/types/PageConfig.ts
packages/web-platform/web-core/index.css
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/apis/inShadowRootStyles.ts
packages/web-platform/web-core/src/uiThread/crossThreadHandlers/bootTimingSystem.ts
packages/web-platform/web-core/src/uiThread/crossThreadHandlers/registerFlushElementTreeHandler.ts
packages/web-platform/web-core/src/utils/browser.ts
packages/web-platform/web-elements/src/XOverlayNg/XOverlayAttributes.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/utils/processStyleInfo.ts
packages/web-platform/web-tests/shell-project/mainthread-test.ts
packages/web-platform/web-tests/tests/react.spec.ts

Before this commit, we have been detecting if current browser supports the `@scope` rule.
This allows us to scope one lynx-view's styles.
After this commit we always create a shadowroot to scope then.
Also for the new shadowroot pattern, we add a new **attribute** `inject-head-links`.
By default, we will iterate all `<link rel="stylesheet">` in the `<head>`, and use `@import url()` to import them inside the shadowroot.
Developers could add a `inject-head-links="false"` to disable this behavior.
#51

feat: use shadowroot to isolate one lynx-view

---

.changeset/seven-foxes-read.md
packages/rspeedy/plugin-react/src/css.ts
packages/rspeedy/plugin-react/test/css.test.ts

When using scoped CSS, the CSS minification is not enabled now.

fix(rspeedy/react): enable CSS minification

---

.changeset/flat-planes-laugh.md
packages/rspeedy/plugin-react/src/loaders/ignore-css-loader.ts

We need to return a ESM module to make sure that all the modules are strict. So that the IIFE of the entry could be removed.
See https://github.com/webpack/webpack/discussions/18367#discussion-6580398 for details.

fix(rspeedy/react): should return ESM in ignore-css-loader

---

.github/workflows/pre-code-review-check.yml
.github/workflows/test.yml

In the merge queue, the workflows are triggered by the `merge_group`, which means the `github.event.pull_request.number` will be null
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28#event-object-common-properties
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency

ci: fix the merge queue

---

.changeset/rotten-humans-sniff.md
.changeset/sharp-cougars-go.md
packages/web-platform/web-constants/src/constants.ts
packages/web-platform/web-constants/src/types/MainThreadStartConfigs.ts
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/uiThread/crossThreadHandlers/registerFlushElementTreeHandler.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-tests/shell-project/mainthread-test.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts
packages/webpack/web-webpack-plugin/src/constants.ts

After the PR #198
All contents are isolated by a shadowroot.
Therefore we don't need to add the entryId selector to avoid the lynx-view's style taking effect on the whole page.

refactor: remove entryId concept

---

.changeset/afraid-shirts-try.md
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-constants/src/types/MainThreadStartConfigs.ts
packages/web-platform/web-constants/src/types/NativeModules.ts
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-explorer/index.ts
packages/web-platform/web-tests/shell-project/index.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNapiLoader.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeModules.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/startBackgroundThread.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts

feat: `nativeModulesUrl` of lynx-view is changed to `nativeModulesMap`, and the usage is completely aligned with `napiModulesMap`.
"warning: This is a breaking change."
`nativeModulesMap` will be a map: key is module-name, value should be a esm url which export default a
function with two parameters(you never need to use `this`):
- `NativeModules`: oriented `NativeModules`, which you can use to call
other Native-Modules.
- `NativeModulesCall`: trigger `onNativeModulesCall`, same as the deprecated `this.nativeModulesCall`.
example:
```js
const nativeModulesMap = {
CustomModule: URL.createObjectURL(
new Blob(
[
`export default function(NativeModules, NativeModulesCall) {
return {
async getColor(data, callback) {
const color = await NativeModulesCall('getColor', data);
callback(color);
},
} …
```

feat(web):  nativeModulesUrl  of lynx-view is changed to nativeModulesMap

---

.changeset/deep-words-hope.md
packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts

Closes #179 
Change the process stage where the `main.lynx.bundle` file is located in order to be able to attach mid-process.

feat: expose `main.lynx.bundle` file to compiler

---

.changeset/hot-crabs-pick.md
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-core/src/uiThread/crossThreadHandlers/registerFlushElementTreeHandler.ts
packages/web-platform/web-core/src/uiThread/decodeElementOperation.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/attributeAndProperty/attributeAndPropertyFunctions.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/attributeAndProperty/createAttributeAndPropertyFunctionsWithContext.ts

move the timing flags collecting into element api.
This will help #51

refactor: clean the decodeOperations implementation

---

.changeset/five-cooks-greet.md
packages/react/etc/react.api.md
packages/react/types/react.docs.d.ts

fix(react): add typing for `useErrorBoundary`

---

.changeset/small-icons-hunt.md
packages/react/runtime/__test__/ssr.test.jsx
packages/react/runtime/__test__/utils/envManager.ts
packages/react/runtime/__test__/utils/globals.js
packages/react/runtime/__test__/utils/nativeMethod.ts
packages/react/runtime/src/lifecycle/render.ts
packages/react/runtime/src/list.ts
packages/react/runtime/src/lynx/calledByNative.ts
packages/react/runtime/src/opcodes.ts
packages/react/runtime/src/root.ts
packages/react/runtime/types/types.d.ts
packages/rspeedy/plugin-react/etc/react-rsbuild-plugin.api.md
packages/rspeedy/plugin-react/src/entry.ts
packages/rspeedy/plugin-react/src/pluginReactLynx.ts
packages/webpack/react-webpack-plugin/etc/react-webpack-plugin.api.md
packages/webpack/react-webpack-plugin/src/ReactWebpackPlugin.ts

In this PR, we add support for Lynx SSR by adding two call-by-native api `ssrEncode` and `ssrHydrate`.

feat(react): support lynx ssr

---

.changeset/loud-signs-see.md
packages/webpack/runtime-wrapper-webpack-plugin/src/RuntimeWrapperWebpackPlugin.ts

The `window` is `undefined` in Lynx. It's useful to distinguish between Lynx and the Web.

chore: add window var to define callback argument in `background.js`

---

.changeset/tasty-months-rush.md
packages/rspeedy/plugin-react-alias/package.json
packages/rspeedy/plugin-react-alias/src/index.ts
packages/rspeedy/plugin-react-alias/test/include.test.ts
packages/rspeedy/plugin-react-alias/vitest.config.ts
packages/rspeedy/plugin-react/src/pluginReactLynx.ts
packages/rspeedy/plugin-react/test/swc-config.test.ts
pnpm-lock.yaml

The react set in the `source.include` is not correct when using canary version.
https://github.com/lynx-family/lynx-stack/blob/33a64cffba578bba9240eb491d5886e1e41467b9/packages/rspeedy/plugin-react/src/pluginReactLynx.ts#L365-L371
We should use `require.resolve` from `rootPath` just like aliases does.

fix(rspeedy/react): use React from `rootPath`

---

packages/web-platform/offscreen-document/Notice.txt
packages/web-platform/offscreen-document/README.md
packages/web-platform/offscreen-document/package.json
packages/web-platform/offscreen-document/src/index.ts
packages/web-platform/offscreen-document/src/main/index.ts
packages/web-platform/offscreen-document/src/main/initOffscreenDocument.ts
packages/web-platform/offscreen-document/src/types/ElementOperation.ts
packages/web-platform/offscreen-document/src/types/index.ts
packages/web-platform/offscreen-document/src/webworker/OffscreenCSSStyleDeclaration.ts
packages/web-platform/offscreen-document/src/webworker/OffscreenDocument.ts
packages/web-platform/offscreen-document/src/webworker/OffscreenElement.ts
packages/web-platform/offscreen-document/src/webworker/OffscreenEvent.ts
packages/web-platform/offscreen-document/src/webworker/index.ts
packages/web-platform/offscreen-document/tsconfig.json
packages/web-platform/tsconfig.json
pnpm-lock.yaml

We're splitting cross-threads dom implementation with the Element PAPI implmenetation.
The Element PAPI will be migrate to this package.
Split current mainthread dom apis into a new package and submit a new WICG proposal for OffscreenDocument #51

feat(web): add a new package @lynx-js/offscreen-document

---

packages/webpack/test-tools/src/case.ts
packages/webpack/test-tools/src/diagnostic.ts

This should fix the flaky test [here](https://github.com/lynx-family/lynx-stack/actions/runs/14055011715/job/39352668039).

test(webpack): use different paths for output

---

.changeset/rude-bears-brake.md
packages/web-platform/web-mainthread-apis/src/elementAPI/style/styleFunctions.ts
packages/web-platform/web-tests/tests/main-thread-apis.test.ts
packages/web-platform/web-tests/tests/react.spec.ts

the inline style value could be incorrectly removed for number value `0`;
For example, `flex-shrink:0` may be ignored.
fix #171

fix: inline style will be removed for value number `0`

---

codecov.yml

> **Deprecation of GitHub Annotations Due to API Limitations**
>
> GitHub Annotations will be deprecated due to the following API constraints:
> 
> The GitHub API does not provide a way to clear annotations once they are sent. Even if subsequent reports processed by Codecov include updated coverage data, previous annotations remain.
>
> Annotations do not work if "Flags" or "Components" are configured, due to conflicts with these features.
>
> https://docs.codecov.com/docs/github-checks

chore: turn-off codecov github annotations

---

.changeset/some-swans-stop.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/output/dist-path.ts
packages/rspeedy/core/src/config/output/index.ts
packages/rspeedy/core/test/config/output.test-d.ts
packages/rspeedy/core/test/config/validate.test.ts

feat(rspeedy/core): add `output.distPath.*`

---

.changeset/silly-tigers-think.md
packages/webpack/react-webpack-plugin/src/LynxProcessEvalResultRuntimeModule.ts
packages/webpack/react-webpack-plugin/test/cases/code-splitting/eval-result/index.jsx

Similar with https://github.com/lynx-family/lynx-stack/pull/170. Some lazy bundles might either fail to return or provide a non-webpack chunk.

fix(webpack/react): NPE when return non-webpack chunk

---

packages/web-platform/web-tests/package.json
packages/web-platform/web-tests/shell-project/index.ts
packages/web-platform/web-tests/shell-project/lynx-view.ts

web-tests adds public configuration export of lynxView, which is to synchronize the break change of lynxView

chore(web): add export lynx-view tests for other projects

---

.changeset/curvy-wasps-count.md
cspell.jsonc
packages/web-platform/web-elements/src/XText/XText.ts
packages/web-platform/web-elements/src/XView/XView.ts
packages/web-platform/web-elements/src/common/CommonEventsAndMethods.ts
packages/web-platform/web-tests/tests/web-elements.spec.ts
packages/web-platform/web-tests/tests/web-elements/x-text/event-layoutchange.html
packages/web-platform/web-tests/tests/web-elements/x-view/event-layoutchange.html

feat: add layoutchange event support for x-view and x-text

---

.changeset/olive-corners-work.md
packages/web-platform/web-core/src/apis/LynxView.ts

Attributes should be hyphen-name: 'init-data', 'global-props'.
now all properties has corresponding attributes.

docs: fix documents about lynx-view's properties

---

.changeset/modern-keys-spend.md
packages/rspeedy/core/src/cli/commands.ts
packages/rspeedy/core/src/cli/dev.ts
packages/rspeedy/core/src/cli/preview.ts
website/docs/en/guide/cli.md
website/docs/zh/guide/cli.md

As one of several PRs addressing issue #304
Support cli flag --base to specify the base path of the server.

feat(rspeedy/core): support cli flag --base

---

.changeset/tender-lemons-film.md
packages/rspeedy/plugin-react/src/css.ts
packages/webpack/css-extract-webpack-plugin/etc/css-extract-webpack-plugin.api.md
packages/webpack/css-extract-webpack-plugin/src/CssExtractRspackPlugin.ts
packages/webpack/template-webpack-plugin/etc/template-webpack-plugin.api.md
packages/webpack/template-webpack-plugin/src/LynxEncodePlugin.ts
packages/webpack/template-webpack-plugin/src/css/encode.ts
packages/webpack/template-webpack-plugin/src/index.ts
packages/webpack/template-webpack-plugin/test/css.test.ts

fix: add enableCSSInvalidation for encodeCSS of css HMR

---

packages/rspeedy/plugin-react/package.json

We already have a `turbo build` run in publishing.
This patch avoid an extra `turbo build` when publishing.

chore: remove useless `prepublishOnly` script

---

.changeset/petite-bobcats-travel.md
packages/react/runtime/__test__/lifecycle/reload.test.jsx
packages/react/runtime/__test__/snapshot/ref.test.jsx
packages/react/runtime/src/lifecycle/destroy.ts
packages/react/runtime/src/lifecycle/event/delayLifecycleEvents.ts
packages/react/runtime/src/lynx-api.ts
packages/react/runtime/src/lynx/tt.ts

This PR fixes a critical issue in the React runtime's lifecycle event handling, specifically in the background thread async render mode. The problem was that ref lifecycle events were being triggered before firstScreen events, which could lead to undefined refs when components try to access them.
The root cause was in the event ordering in the background thread. In the async render mode, we need to ensure that firstScreen events complete before ref events are processed, as components may depend on the firstScreen state being fully initialized.
The fix ensures proper event ordering by:
1. Modifying the lifecycle event delay mechanism
2. Updating the ref event handling to wait for firstScreen completion
3. Adding comprehensive test cases to verify the correct event sequence
This change …

fix(react/runtime): ensure `ref` lifecycle events run after `firstScreen`

---

.changeset/sweet-crabs-travel.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/dev/index.ts
packages/rspeedy/core/src/plugins/dev.plugin.ts
packages/rspeedy/core/test/config/dev.test-d.ts
packages/rspeedy/core/test/plugins/dev.plugin.test.ts

feat(rspeedy/core): add `dev.hmr` and `dev.liveReload`

---

packages/rspeedy/core/package.json
packages/rspeedy/core/rslib.config.ts
packages/rspeedy/core/turbo.json
pnpm-lock.yaml

Fix a regression from #470: "Cannot find package 'ts-blank-space' imported from @lynx-js/rspeedy/register/hooks.js"

fix(rspeedy/core): bundle ts-blank-space

---

packages/rspeedy/core/package.json
packages/rspeedy/core/rslib.config.ts

Fix a regression of #475: "Error on typia.createValidateEquals(): no transform has been configured."

fix(rspeedy/core): should run typia transform on CLI

---

packages/rspeedy/core/package.json

Fix an regression of #478: "error TS2307: Cannot find module '@lynx-js/rspeedy/register' or its corresponding type declarations."
> https://github.com/lynx-family/lynx-stack/actions/runs/14280496355/job/40029566753

fix(rspeedy/core): avoid pre-publish build

---

.github/workflows/test.yml
.github/workflows/workflow-test.yml
cspell.jsonc

A new test `test-publish` has been added.
This test setup a mocked NPM registry using `@pnpm/registry-mock` ([verdaccio](https://verdaccio.org/) underhood) and publish all packages to that registry. Then a Rspeedy App will be created and tested using the newly published packages.
This is used to avoid future regression like: #475, #478 and #479.

ci: add test-publish

---

.changeset/tired-lamps-attend.md
packages/rspeedy/core/package.json
pnpm-lock.yaml

Since we are now bundling `ts-blank-space` and externalizing `typescript` (#475), we need to manually specify the `peerDependencies`.
The version requirement is copied from [`ts-blank-space/package.json`](https://github.com/bloomberg/ts-blank-space/blob/4102b1f26b1c53d38a1de74c10f262af5fd34fe8/package.json#L26).
> [!NOTE]
> The `typescript` is not required when:
>
> 1. Using JavaScript (`.js`) configuration
> 1. Using Node.js v23.6+
> 1. Using Node.js v22.6+ with `--experimental-strip-types` or `--experimental-transform-types`

feat(rspeedy/core)!: requires typescript 5.1.6 - 5.8.x

---

.changeset/slick-pianos-beg.md
packages/rspeedy/core/src/config/loadConfig.ts
packages/rspeedy/core/test/config/loadConfig.test.ts
website/docs/en/guide/cli.md
website/docs/zh/guide/cli.md

Node.js v23.6 has unflagged the `--experimental-strip-types` feature (https://github.com/nodejs/node/pull/56350). Instead of relying solely on this flag, it’s recommended to also check the standard `process.feature.typescript` to confirm native TypeScript support.
> [!NOTE]
> It will be backport to v22 soon. See: https://github.com/nodejs/node/pull/57298

feat(rspeedy/core): use `process.features.typescript`

---

.changeset/famous-dryers-play.md
.changeset/seven-cougars-look.md
packages/webpack/template-webpack-plugin/src/LynxEncodePlugin.ts
packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts
packages/webpack/template-webpack-plugin/test/cases/assets/production/rspack.config.js

This patch resolves a regression from issue #231 that prevented obtaining the correct content hash for `background.js`. The fix involves delaying the `processAssets` stage of Encode to `PROCESS_ASSETS_STAGE_OPTIMIZE_HASH`.
The removal of debugging assets is postponed to `compiler.hooks.afterEmit` to ensure accurate retrieval of assets and their corresponding source maps.
close: #251

fix(webpack/template): delay deleting debugging assets

---

.changeset/all-melons-fall.md
packages/web-platform/web-constants/src/constants.ts
packages/web-platform/web-core/src/utils/loadTemplate.ts
packages/web-platform/web-mainthread-apis/src/MainThreadLynx.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/ElementThreadElement.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/event/eventFunctions.ts
packages/web-platform/web-tests/resources/web-core.main-thread.json
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/basic-mts-bindtap/index.jsx
packages/web-platform/web-worker-runtime/src/index.ts
packages/webpack/web-webpack-plugin/src/index.ts

now the main-thread:bindxx handler could be invoked. The params of the handler will be implemented later.
#54

feat: implement mts event handler support and update related constants

---

packages/third-party/tailwind-preset/package.json

Since we are using TypeScript project reference, there is no need to run `tsc --build` in `packages/third-party/tailwind-preset/package.json#scripts.build`.

chore: remove useless build script

---

.changeset/blue-lies-flash.md
packages/web-platform/web-constants/src/types/NativeApp.ts
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/uiThread/bootWorkers.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-tests/shell-project/index.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/api-getSharedData/index.jsx
packages/web-platform/web-tests/tests/react/api-setSharedData/index.jsx
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts

* support `nativeApp.getSharedData` and `nativeApp.setSharedData`
* add the context id for labeling workers. Now for those workers with context id, we will count the number of running cards. We kill those workers only if all lynx card has been killed.

feat: support `shared-context`

---

.changeset/great-masks-mate.md
packages/web-platform/web-elements/src/XList/x-list.css
packages/web-platform/web-tests/tests/web-elements/x-list/basic.html

fix: When list-type is not specified, it is treated as single formatting.

fix(web): When list-type is not specified, it is treated as single

---

.changeset/hot-tools-relax.md
packages/react/runtime/__test__/delayed-lifecycle-events.test.jsx
packages/react/runtime/src/lynx/tt.ts

This fix an edge case when `__FIRST_SCREEN_SYNC_TIMING__ === 'immediately'`, user will run `flushDelayedLifecycleEvents` immediately after preact render,
```js
__root.__jsx = jsx;
renderBackground(jsx, __root as any);
if (__FIRST_SCREEN_SYNC_TIMING__ === 'immediately') {
// This is for cases where `root.render()` is called asynchronously,
// `firstScreen` message might have been reached.
flushDelayedLifecycleEvents();
```
`delayedLifecycleEvents` is:
```json
[
[
"rLynxFirstScreen",
{
"root": "{\\"id\\":-1,\\"type\\":\\"root\\"}",
"refPatch": "{}",
"jsReadyEventIdSwap": {}
}
]
]
```
After run into `onLifecycleEventImpl`, we will run `flushDelayedLifecycleEvents` again, get stack overflow
```js
// TODO: It seems `delayedEvents` and `delayedLifecycleEvents` should be merged into one array to …
```

fix: flushDelayedLifecycleEvents stack overflow  error

---

.changeset/sour-streets-remain.md
packages/web-platform/web-explorer/index.html

rsbuild uses the last script element's url to generate the publich(aka `__webpack_require.p`)

fix: web-explorer crash

---

.changeset/young-parents-fry.md
packages/rspeedy/plugin-react/src/swc.ts
packages/rspeedy/plugin-react/test/swc-config.test.ts

This patch resolves the issue that `tools.swc` cannot be used with `pluginReactLynx`.

fix(rspeedy/react): should allow overriding SWC config

---

.changeset/tidy-lemons-bow.md
packages/web-platform/web-constants/src/types/EventType.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/event/eventFunctions.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/style/styleFunctions.ts
packages/web-platform/web-tests/tests/main-thread-apis.test.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/basic-mts-bindtap-change-element-background/index.jsx

After this commit, developers are allowed to invoke `event.target.setStyleProperty` in mts handler
`__AddInlineStyle`  now supports a raw name as proeprty name, pervious we only accept a number as property id.
#54

feat: support mts event with target methods

---

.changeset/angry-buckets-chew.md
packages/web-platform/web-explorer/index.ts

fix: delay 500ms to send the `webExplorerReady`

---

.changeset/afraid-rivers-float.md
packages/react/runtime/src/index.ts
packages/webpack/react-webpack-plugin/test/cases/code-splitting/load-lazy-bundle/foo.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/load-lazy-bundle/index.jsx
packages/webpack/react-webpack-plugin/test/cases/code-splitting/load-lazy-bundle/rspack.config.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/load-lazy-bundle/test.config.cjs

Fix a regression of #284. Should set `lynx.loadLazyBundle` when using `lazy()`.

fix(react/runtime): should have `lynx.loadLazyBundle`

---

.changeset/bright-forks-try.md
packages/web-platform/web-constants/src/constants.ts
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-constants/src/types/LynxContextEventTarget.ts
packages/web-platform/web-mainthread-apis/src/MainThreadLynx.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/basic-mts-mainthread-ref/index.jsx
packages/web-platform/web-tests/tests/react/basic-mts-run-on-background/index.jsx
packages/web-platform/web-tests/tests/react/basic-mts-run-on-main-thread/index.jsx
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createBackgroundLynx.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts
packages/web-platform/web-worker-runtime/src/common/LynxCrossThreadContext.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts

* mainthread event
* mainthread ref
* runOnMainThread/runOnBackground
* ref.current.xx
After this commit:
* `runWorklet` will be a mutable variable
* implment lynx.getJSContext() on main thread context
* support sending event main <------> bg
close Support MTS #54

feat(web): fully support MTS

---

.changeset/yummy-trains-sort.md
packages/web-platform/web-elements/src/XList/XListEvents.ts
packages/web-platform/web-tests/tests/web-elements.spec.ts
packages/web-platform/web-tests/tests/web-elements/x-list/need-visible-item-info.html

feat: x-list supports `need-visible-item-info`, now you can get visible cells info in `scroll`、`scrolltoupper`、`scrolltolower` event.

feat(web): x-list supports need-visible-item-info

---

.changeset/lucky-eyes-sing.md
packages/web-platform/web-explorer/index.ts

fix: allow lynxjs.org to access native modules

---

.changeset/twenty-singers-talk.md
packages/web-platform/web-mainthread-apis/src/MainThreadLynx.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-tests/tests/web-core.test.ts

fix: mts lynx will no longer provide requireModule, requireModuleAsync methods, which is aligned with Native.

fix(web): remove requireModule, requireModuleAsync of mts

---

.changeset/shaky-games-cough.md
packages/web-platform/web-elements/src/XText/RawText.ts
packages/web-platform/web-tests/tests/lighthouse.cases.js

use `new Text()` to replace innerHTML

perf: improve raw-text performance

---

.changeset/rotten-walls-hear.md
packages/rspeedy/plugin-react-alias/etc/react-alias-rsbuild-plugin.api.md
packages/rspeedy/plugin-react-alias/src/index.ts
packages/rspeedy/plugin-react/package.json
packages/rspeedy/plugin-react/src/background-only/empty.ts
packages/rspeedy/plugin-react/src/background-only/error.ts
packages/rspeedy/plugin-react/src/backgroundOnly.ts
pnpm-lock.yaml

close #600 
Refactor: Replace built-in `background-only` implementation with npm package
Previously we maintained custom files:
- `empty.ts` for background thread
- `error.ts` for main thread validation
Now adopting the standard `background-only` npm package

refactor: adopt background-only npm package

---

.changeset/open-taxis-hear.md
packages/webpack/css-extract-webpack-plugin/src/CssExtractRspackPlugin.ts
packages/webpack/template-webpack-plugin/etc/template-webpack-plugin.api.md
packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts
packages/webpack/template-webpack-plugin/src/css/cssChunksToMap.ts
packages/webpack/template-webpack-plugin/src/css/debundle.ts
packages/webpack/template-webpack-plugin/src/css/encode.ts
packages/webpack/template-webpack-plugin/test/css.test.ts

When the `enableCSSSelector` option is set to false, style rule priority is inversely related to `@import` order(Lynx CSS engine has the incorrect behavior). Reserve the `@import` order to ensure the style rule priority is correct.

fix(css-extract): CSS import order when enableCSSSelector is false

---

.changeset/neat-plants-flash.md
packages/react/runtime/src/list.ts

Refactor: Improved naming for list operation related types. Renamed `UpdateAction` interface to `ListOperations`. This prepares for subsequent refactoring of list operations logic.

refactor(type): list operations

---

.changeset/ready-months-type.md
packages/web-platform/web-constants/src/index.ts
packages/web-platform/web-constants/src/utils/LynxCrossThreadContext.ts
packages/web-platform/web-constants/src/utils/index.ts
packages/web-platform/web-mainthread-apis/src/crossThreadHandlers/registerCallLepusMethodHandler.ts
packages/web-platform/web-mainthread-apis/src/crossThreadHandlers/registerGetCustomSectionHandler.ts
packages/web-platform/web-mainthread-apis/src/index.ts
packages/web-platform/web-mainthread-apis/src/loadMainThread.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createBackgroundLynx.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts

we're going to implement thread mode: `all-on-ui`

refactor: move mainthread impl into mainthread-api packages

---

.changeset/cruel-hornets-burn.md
packages/web-platform/web-constants/src/constants.ts
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-constants/src/types/PageConfig.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/uiThread/bootWorkers.ts
packages/web-platform/web-core/src/utils/loadTemplate.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/loadMainThread.ts
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts
packages/web-platform/web-worker-runtime/src/index.ts

Never assign `SystemInfo` on worker's self object.
This is a step to `all-on-ui`

refactor: isolate SystemInfo

---

.changeset/giant-seas-leave.md
.changeset/slow-tools-ring.md
.github/workflows/test.yml
packages/web-platform/offscreen-document/src/webworker/OffscreenNode.ts
packages/web-platform/web-core/package.json
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/uiThread/bootWorkers.ts
packages/web-platform/web-core/src/uiThread/createRenderAllOnUI.ts
packages/web-platform/web-core/src/uiThread/createRenderMultiThread.ts
packages/web-platform/web-core/src/uiThread/crossThreadHandlers/createUpdateData.ts
packages/web-platform/web-core/src/uiThread/startBackground.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/loadMainThread.ts
packages/web-platform/web-tests/playwright.config.ts
packages/web-platform/web-tests/rspack.config.js
packages/web-platform/web-tests/shell-project/index.ts
packages/web-platform/web-tests/shell-project/web-core.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/web-core.test.ts
packages/web-platform/web-worker-rpc/src/Rpc.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts
pnpm-lock.yaml

```html
<lynx-view thread-strategy="all-on-ui"></lynx-view>
```
This will make the lynx's main-thread run on the UA's main thread.
Note that the `all-on-ui` dose not support the HMR & chunk splitting yet, related tests are disabled.

feat: support thread strategy all on ui

---

.changeset/silly-rocks-guess.md
packages/react/runtime/__test__/lifecycle.test.jsx
packages/react/runtime/__test__/lynx/timing.test.jsx
packages/react/runtime/__test__/snapshot/gesture.test.jsx
packages/react/runtime/__test__/snapshot/ref.test.jsx
packages/react/runtime/__test__/snapshot/workletEvent.test.jsx
packages/react/runtime/__test__/snapshot/workletRef.test.jsx
packages/react/runtime/__test__/worklet/workletRef.test.jsx
packages/react/runtime/src/lifecycle/destroy.ts
packages/react/runtime/src/lifecycle/patch/commit.ts
packages/react/runtime/src/lifecycle/reload.ts
packages/react/runtime/src/lifecycle/render.ts
packages/react/runtime/src/lynx-api.ts
packages/react/runtime/src/lynx/tt.ts
packages/react/testing-library/src/__tests__/worklet.test.jsx
packages/react/testing-library/src/pure.jsx
packages/react/testing-library/src/vitest-global-setup.js

Reverts #239: "batch multiple patches for main thread communication"
This reverts the change that batched updates sent to the main thread in a single render pass.

fix(react/runtime): revert #239 'batch multiple patches for main thread communication'

---

.changeset/silly-rocks-guess.md
packages/react/runtime/__test__/lifecycle.test.jsx
packages/react/runtime/__test__/lynx/timing.test.jsx
packages/react/runtime/__test__/snapshot/gesture.test.jsx
packages/react/runtime/__test__/snapshot/ref.test.jsx
packages/react/runtime/__test__/snapshot/workletEvent.test.jsx
packages/react/runtime/__test__/snapshot/workletRef.test.jsx
packages/react/runtime/__test__/worklet/workletRef.test.jsx
packages/react/runtime/src/lifecycle/destroy.ts
packages/react/runtime/src/lifecycle/patch/commit.ts
packages/react/runtime/src/lifecycle/reload.ts
packages/react/runtime/src/lifecycle/render.ts
packages/react/runtime/src/lynx-api.ts
packages/react/runtime/src/lynx/tt.ts
packages/react/testing-library/src/__tests__/worklet.test.jsx
packages/react/testing-library/src/pure.jsx
packages/react/testing-library/src/vitest-global-setup.js

Reverts lynx-family/lynx-stack#637

fix(react/runtime): un-revert #239 'batch multiple patches for main thread communication'

---

.changeset/brave-ants-report.md
.changeset/empty-worms-buy.md
.changeset/loud-mangos-enjoy.md
.cspell/lynx.txt
packages/web-platform/offscreen-document/src/main/initOffscreenDocument.ts
packages/web-platform/web-constants/src/types/Cloneable.ts
packages/web-platform/web-constants/src/types/PageConfig.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/utils/createCrossThreadEvent.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/api-SystemInfo-height-width/index.jsx
packages/web-platform/web-tests/tests/react/basic-mts-bindtouchstart/index.jsx
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts

* add touch event support for offscreen-dom
* add touch properties support for bts and mts event handlers
* add SystemInfo.screenWidth and SystemInfo.screenHeight
close #54

feat: support touch events for MTS

---

.changeset/modern-peaches-marry.md
.github/workflows/test.yml
.gitignore
packages/web-platform/web-explorer/package.json
packages/web-platform/web-explorer/rsbuild.config.ts
packages/web-platform/web-rsbuild-plugin/README.md
packages/web-platform/web-rsbuild-plugin/api-extractor.json
packages/web-platform/web-rsbuild-plugin/package.json
packages/web-platform/web-rsbuild-plugin/rslib.config.ts
packages/web-platform/web-rsbuild-plugin/src/index.ts
packages/web-platform/web-rsbuild-plugin/src/pluginWebPlatform.ts
packages/web-platform/web-rsbuild-plugin/tests/__snapshots__/config.test.ts.snap
packages/web-platform/web-rsbuild-plugin/tests/config.test.ts
packages/web-platform/web-rsbuild-plugin/tsconfig.json
packages/web-platform/web-rsbuild-plugin/turbo.json
packages/web-platform/web-rsbuild-plugin/vitest.config.ts
pnpm-lock.yaml

feat: Provides Rsbuild plugin for Web projects in Lynx Web Platform, currently supports polyfill about lynx.
#546

feat(web): supports rsbuild plugin for Web projects in Lynx Web Platform

---

.changeset/fifty-moose-boil.md
packages/rspeedy/plugin-react/src/entry.ts
packages/rspeedy/plugin-react/test/basic.test.ts
packages/rspeedy/plugin-react/test/fixtures/special-var-name/Behavior.jsx
packages/rspeedy/plugin-react/test/fixtures/special-var-name/Card/Card.js
packages/rspeedy/plugin-react/test/fixtures/special-var-name/Component.js
packages/rspeedy/plugin-react/test/fixtures/special-var-name/ReactLynx/index.js
packages/rspeedy/plugin-react/test/fixtures/special-var-name/index.jsx

Modules or variables with specific names like `Behavior`, `Card`, `Component`, or `ReactLynx` may conflict with parameters injected by the runtime wrapper.
```js
function (ReactLynx) {
let ReactLynx = 42 // <-- SyntaxError: Identifier 'ReactLynx' has already been declared
}
```
We are renaming these unused variables to prevent any conflicts with existing variables.

fix(rspeedy/react): avoid error when using special var names

---

.changeset/fine-ants-rush.md
packages/web-platform/web-explorer/index.html

fix: loading errors caused by script import order

fix(web): loading errors caused by script import order

---

.github/workflows/deploy-main.yml

> Error: The artifact name is not valid: refs/heads/release/react-0-107-x-e2326f34961375f0ea32b842b7ad62fa9479a050. Contains the following character:  Forward slash /
>
> https://github.com/lynx-family/lynx-stack/actions/runs/14751119946/job/41408647299

ci: cannot use `github.ref` as artifact name

---

.changeset/deep-heads-talk.md
.changeset/hot-adults-wear.md
.changeset/thick-pots-clap.md
packages/web-platform/tsconfig.json
packages/web-platform/web-explorer/index.native-modules.ts
packages/web-platform/web-explorer/index.ts
packages/web-platform/web-explorer/rsbuild.config.ts
packages/web-platform/web-rsbuild-plugin/README.md
packages/web-platform/web-rsbuild-plugin/package.json
packages/web-platform/web-rsbuild-plugin/src/loaders/native-modules.ts
packages/web-platform/web-rsbuild-plugin/src/pluginWebPlatform.ts
packages/web-platform/web-rsbuild-plugin/tests/bundle.test.ts
packages/web-platform/web-rsbuild-plugin/tests/fixtures/index.native-modules.ts
packages/web-platform/web-rsbuild-plugin/tests/fixtures/index.ts
packages/web-platform/web-rsbuild-plugin/tests/tsconfig.json
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeModules.ts
pnpm-lock.yaml

feat: add new parameter `nativeModulesPath` to `pluginWebPlatform({})`.
After this commit, you can use `nativeModulesPath` to package custom nativeModules directly into the worker, and no longer need to pass nativeModulesMap to lynx-view.
Here is an example:
- `native-modules.ts`:
```ts
// index.native-modules.ts
export default {
CustomModule: function(NativeModules, NativeModulesCall) {
return {
async getColor(data, callback) {
const color = await NativeModulesCall('getColor', data);
callback(color);
},
};
},
};
```
- plugin config:
```ts
// rsbuild.config.ts
import { pluginWebPlatform } from '@lynx-js/web-platform-rsbuild-plugin';
import { defineConfig } from '@rsbuild/core';
export default defineConfig({
plugins: [pluginWebPlatform({
// replace with your actual native-modules file path …
```

feat(web): add nativeModules config to bundle it into worker

---

.changeset/hip-toes-admire.md
packages/react/runtime/lazy/import.js
packages/react/transform/__test__/fixture.spec.js
packages/react/transform/src/swc_plugin_dynamic_import/mod.rs
packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_dynamic_import/mod.rs/should_not_import_lazy.js
packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_dynamic_import/mod.rs/should_transform_import_call.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/lazy-imports/index.jsx
packages/webpack/react-webpack-plugin/test/cases/code-splitting/lazy-imports/rspack.config.js
packages/webpack/react-webpack-plugin/test/cases/code-splitting/lazy-imports/test.config.cjs

Similar with #666.
We would like to avoid the manually imported `@lynx-js/react/experimental/lazy/import` (which is easy to forget).
This patch auto imports the lazy runtimes when `import(url)` is used.
> [!NOTE]
> The lazy runtime is only needed when using an external `import()` (e.g.: `https://` or a variable).

feat(react/transform): auto import lazy runtime when using `import()`

---

packages/react/transform/src/swc_plugin_worklet/extract_ident.rs
packages/react/transform/src/swc_plugin_worklet/gen_stmt.rs

Refactor MTS `js_fns_to_extract` to make props keys and values accessible.

refactor(react/transform): MTS `js_fns_to_extract` to make props keys and values accessible

---

.changeset/young-seals-train.md
packages/testing-library/test-environment/package.json
packages/testing-library/test-environment/rslib.config.ts
packages/testing-library/test-environment/src/index.ts
packages/testing-library/test-environment/src/lynx/GlobalThis.ts
packages/testing-library/test-environment/turbo.json
pnpm-lock.yaml

There are some publint and TypeScript error when using `@lynx-js/test-environment`:
> https://publint.dev/@lynx-js/test-environment@0.0.1
```
Running publint v0.3.12 for @lynx-js/test-environment...
Packing files with `pnpm pack`...
Linting...
Errors:
1. pkg.exports["."].types should be the first in the object as conditions are order-sensitive so it can be resolved by TypeScript.
2. pkg.exports["."].default should be the last in the object so it doesn't take precedence over the keys following it.
3. pkg.exports["./env/vitest"].types should be the first in the object as conditions are order-sensitive so it can be resolved by TypeScript.
4. pkg.exports["./env/vitest"].default should be the last in the object so it doesn't take precedence over the keys following it.
Warnings:
1. …
```

refactor(test-environment): fix publint error

---

.changeset/cuddly-beans-enter.md
cspell.jsonc
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/api-queueMicrotask/index.jsx
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createBackgroundLynx.ts

feat: support for using `lynx.queueMicrotask`.

feat(web): support for using lynx.queueMicrotask.

---

packages/background-only/README.md
packages/background-only/empty.js
packages/background-only/error.js
packages/background-only/index.d.ts
packages/background-only/package.json
packages/background-only/tsconfig.json
pnpm-workspace.yaml
tsconfig.json

Add back background-only package to monorepo.
Note that the package was already published to npm: https://www.npmjs.com/package/background-only

feat(background-only): add source and integrate into monorepo

---

packages/rspeedy/plugin-react/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Following up #711, use the `background-only` package from workspace.

chore(rspeedy/react): use `background-only` from workspace

---

.changeset/full-rocks-smoke.md
.changeset/good-eagles-laugh.md
packages/rspeedy/plugin-react/src/entry.ts
packages/rspeedy/plugin-react/test/config.test.ts
packages/webpack/react-webpack-plugin/src/ReactWebpackPlugin.ts

Following up #691. Use `performance.profile` to inject runtime profile in ReactLynx.

feat(rspeedy/react): support `performance.profile`

---

packages/react/README.md
packages/react/runtime/package.json
packages/react/runtime/src/backgroundSnapshot.ts
packages/react/runtime/src/document.ts
packages/react/runtime/src/lifecycle/delayUnmount.ts
packages/react/runtime/src/lifecycle/patch/commit.ts
packages/react/runtime/src/lifecycle/patch/snapshotPatch.ts
packages/react/runtime/src/lifecycle/patch/snapshotPatchApply.ts
packages/react/runtime/src/lifecycle/reload.ts
packages/react/runtime/src/lifecycle/render.ts
packages/react/runtime/src/lynx-api.ts
packages/react/runtime/src/lynx.ts
packages/react/runtime/src/renderToOpcodes/index.ts
packages/react/runtime/src/root.ts
packages/react/runtime/src/snapshot.ts
packages/react/runtime/src/snapshot/ref.ts
packages/react/runtime/src/snapshot/spread.ts
packages/react/runtime/types/types.d.ts

This diff does 3 things:
- add Reanimated, RSC and others into README
- try to help with https://github.com/lynx-family/lynx-stack/issues/726 whenever I see it
- add doc comments for files to clarify understandings for all

docs(react): README; add some comments; deprecate some old macros

---

.github/workflows/relative-ci.yml

We should use different key for different projects in a monorepo.

ci: use different keys for different projects

---

.changeset/cold-terms-battle.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/rsbuild/index.ts
packages/rspeedy/core/src/config/source/index.ts
packages/rspeedy/core/test/config/rsbuild.test.ts
packages/rspeedy/core/test/config/source/preEntry.test-d.ts
packages/rspeedy/core/test/config/validate.test.ts
packages/webpack/react-webpack-plugin/etc/react-webpack-plugin.api.md

close #299
When we set `preEntry` in the `lynx.config.js`:
```js
source: {
entry: {
main: './src/index.tsx',
main2: './src/index.tsx',
},
preEntry: './src/normalize.css',
},
```
The `rspack.config.lynx.mjs` will automatically generate entries with the following structure:
```js
main__main-thread: {
layer: 'react:main-thread',
'import': [
'/hotModuleReplacement.lepus.cjs',
'./src/normalize.css',
'./src/index.tsx'
],
filename: '.rspeedy/main/main-thread.js'
},
main: {
layer: 'react:background',
'import': [
'@lynx-js/react/refresh',
'@lynx-js/webpack-dev-transport/client',
'@rspack/core/hot/dev-server',
'./src/normalize.css',
'./src/index.tsx'
],
filename: '.rspeedy/main/background.js'
},
main2__main-thread: {
layer: 'react:main-thread',
'import': [
'/hotModuleReplacement.lepus.cjs', …
```

feat(rspeedy): support source.preEntry

---

.github/workflows/relative-ci.yml
.github/workflows/workflow-bundle-analysis.yml
packages/rspeedy/core/rslib.config.ts
packages/rspeedy/core/turbo.json

Add the Rspeedy to RelativeCI to monitor the bundle size change.
See https://app.relative-ci.com/projects/IlmtJm9v1Hh532Ir067b

ci: add Rspeedy to RelativeCI

---

.changeset/little-candies-carry.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/create-rspeedy.ts
packages/rspeedy/core/test/createRspeedy.test.ts

Set the `callerName` option of `createRsbuild`, which can be accessed by Rsbuild plugins through `api.context.callerName`.
See:
- https://github.com/web-infra-dev/rsbuild/pull/5204
- https://github.com/web-infra-dev/rslib/pull/974

feat(rspeedy/core): add `callerName` option to `createRspeedy`

---

.github/workflows/relative-ci.yml

ci: add missing `RELATIVE_CI_PROJECT_RSPEEDY_CORE_KEY`

---

packages/web-platform/web-tests/package.json

Fix [Rspack EcoSystem CI failure](https://github.com/web-infra-dev/rspack/actions/runs/14986731044/job/42102260301) (since `CI` could be something like `true` or `github`).
This would also make web-tests:build work on Windows.

chore(web-tests): use `is-ci` instead of shell

---

.changeset/sweet-tires-flash.md
packages/webpack/runtime-wrapper-webpack-plugin/src/RuntimeWrapperWebpackPlugin.ts
packages/webpack/runtime-wrapper-webpack-plugin/test/cases.test.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/request-animation-frame/index.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/request-animation-frame/rspack.config.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/request-animation-frame/webpack.config.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/websocket/index.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/websocket/rspack.config.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/websocket/webpack.config.js

Allow direct access to `requestAnimationFrame` and `cancelAnimationFrame` in background thread script.
close: #181 since `fetch` is now a parameter of the runtime wrapper.

feat(webpack/runtime-wrapper): support `requestAnimationFrame`

---

.github/workflows/deploy-main.yml
.github/workflows/workflow-test.yml

Fix a regression of #646. The event name should be `merge_group` instead of `merge_queue`. See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group.
Also fix an issue that `publish` and `build-all` share the same `concurrency.group`.

ci: upload test results in merge queue to main context

---

.changeset/gold-chefs-obey.md
packages/web-platform/web-constants/src/constants.ts
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/inShadowRootStyles.ts
packages/web-platform/web-tests/shell-project/index.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/api-inject-style-rules/index.jsx

This property allows developer to inject some style rules into the shadowroot.
It's a wrapper of https://developer.mozilla.org/docs/Web/API/CSSStyleSheet/insertRule

feat: add new property `inject-style-rules` for LynxView

---

.changeset/common-games-hope.md
packages/webpack/webpack-dev-transport/client/reloadApp.ts
packages/webpack/webpack-dev-transport/test/client/reloadApp.test.ts

Adopt the new `LynxDevToolSetModule.invokeCdp` method introduced in Lynx 3.3.
See: https://github.com/lynx-family/lynx/commit/d278c8fa1bc5d24dfe25e6a23c2cdf8a31669ef0
This would make `dev.liveReload` work.
fix: #657 
fix: https://github.com/lynx-family/lynx/issues/698

fix(webpack-dev-transport): apply the new `LynxDevToolSetModule`

---

.changeset/busy-hounds-take.md
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/loadMainThread.ts
packages/web-platform/web-tests/shell-project/mainthread-test.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/basic-globalThis-property-bts/index.jsx
packages/web-platform/web-tests/tests/react/basic-globalThis-property-mts/index.jsx
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts

```
globalThis.Reflect; // this will be the Reflect Object
```
Note that `assigning to the globalThis` is still not allowed.
fix #716

feat: allow lynx code to get JS engine provided properties on globalThis

---

.changeset/five-boats-fix.md
packages/webpack/template-webpack-plugin/src/LynxEncodePlugin.ts
packages/webpack/template-webpack-plugin/test/cases/assets/production/rspack.config.js
packages/webpack/web-webpack-plugin/src/index.ts

fix: #763
We move the deleting from `compiler.hooks.emit` to `compilation.hooks.processAssets` to avoid having inlined JS chunks in manifest generated by `rspack-manifest-plugin`.
Here is the new timeline:
- `processAssets`
- stage `PROCESS_ASSETS_STAGE_OPTIMIZE_HASH`: generate `.lynx.bundle`
- stage `PROCESS_ASSETS_STAGE_REPORT`: upload source-map or assets map (see: https://github.com/lynx-family/lynx-stack/issues/179)
- stage `PROCESS_ASSETS_STAGE_REPORT` + 1: delete inlined assets (`main-thread.js`, `background.[hash].js`)
- stage `Inifity`: generating manifest (see: #763)

fix(webpack/template): delete inlined assets in `processAssets`

---

packages/react/worklet-runtime/__test__/workletRuntime.test.js
packages/react/worklet-runtime/src/ctxTrace.ts
packages/react/worklet-runtime/src/workletRuntime.ts

Allow the framework to get the currently running main thread function ctx.

feat(react/runtime): add context tracking for worklet execution

---

.github/workflows/test.yml
.github/workflows/workflow-bundle-analysis.yml

Since we are not requiring RelativeCI, we can remove it from merge queue to same some job runs.

ci: disable bundle-analysis in merge queue

---

.github/workflows/deploy-main.yml
.github/workflows/nodejs-dependencies.yml
.github/workflows/rust.yml
.github/workflows/stale.yml
.github/workflows/test.yml
.github/workflows/workflow-test.yml

Set `permissions: {}` for all workflows. And set required permissions for each job.
Fix: https://github.com/lynx-family/lynx-stack/security/code-scanning/124
See https://docs.zizmor.sh/audits/#excessive-permissions for more details.

ci: set default minimum permissions

---

.changeset/good-falcons-sort.md
packages/web-platform/web-core/src/uiThread/bootWorkers.ts
packages/web-platform/web-tests/tests/react.spec.ts

fix: worker not released when backgroundWorkerContextCount != 1
#821

fix: worker not released when backgroundWorkerContextCount != 1

---

.changeset/fresh-terms-guess.md
packages/web-platform/web-elements/src/XImage/x-image.css
packages/web-platform/web-elements/src/XInput/x-input.css
packages/web-platform/web-elements/src/XOverlayNg/x-overlay-ng.css
packages/web-platform/web-elements/src/XRefreshView/x-refresh-view.css
packages/web-platform/web-elements/src/XText/x-text.css
packages/web-platform/web-elements/src/XTextarea/x-textarea.css
packages/web-platform/web-elements/src/XViewpagerNg/x-viewpager-ng.css

Before this commit, we don't allow developers to render these elements before they're defined.
In this commit, we will remove these restrictions.

refactor: allow elements to be rendered before :defined

---

.changeset/afraid-meals-attend.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/defaults.ts
packages/rspeedy/core/src/config/output/index.ts
packages/rspeedy/core/test/config/output.test-d.ts
packages/rspeedy/core/test/config/validate.test.ts
packages/rspeedy/plugin-react/src/entry.ts
packages/webpack/template-webpack-plugin/etc/template-webpack-plugin.api.md
packages/webpack/template-webpack-plugin/src/LynxEncodePlugin.ts
packages/webpack/template-webpack-plugin/test/cases/inline-scripts/external/foo.js
packages/webpack/template-webpack-plugin/test/cases/inline-scripts/external/index.js
packages/webpack/template-webpack-plugin/test/cases/inline-scripts/external/rspack.config.js
packages/webpack/template-webpack-plugin/test/cases/inline-scripts/inline/foo.js
packages/webpack/template-webpack-plugin/test/cases/inline-scripts/inline/index.js
packages/webpack/template-webpack-plugin/test/cases/inline-scripts/inline/rspack.config.js

#870  
follow up #502
Support `output.inlineScripts`, which controls whether to inline scripts files when LynxEncodePlugin generates the manifest file.

feat: support output.inlineScripts

---

.changeset/cold-corners-agree.md
.changeset/fair-pears-smile.md
packages/react/runtime/src/lifecycle/patch/snapshotPatchApply.ts
packages/react/runtime/src/snapshot.ts
packages/react/testing-library/src/__tests__/lazy-bundle/LazyComponent.jsx
packages/react/testing-library/src/__tests__/lazy-bundle/index.test.jsx
packages/react/testing-library/src/vitest-global-setup.js

Fixes #852
In the testing library, we do not need HMR for snapshots because `snapshotManager` is always created when the test is started. This is fixed by correcting the `SnapshotOperation.DEV_ONLY_AddSnapshot`'s checking logic.

feat(testing-library): support lazy bundle testing

---

.changeset/few-stars-write.md
examples/react/test/jsx-runtime.test-d.tsx
packages/react/runtime/jsx-runtime/index.d.ts
packages/react/types/react.d.ts

Add `key` to `JSX.IntrinsicAttributes`.
```jsx
<Foo key='foo' />
^^^ Type '{ key: string; }' is not assignable to type 'IntrinsicAttributes'.
Property 'key' does not exist on type 'IntrinsicAttributes'.ts(2322)
```
> [!NOTE]
> We did not extends `React.JSX.IntrinsicAttributes` like [`@types/react`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/981449c691b9be0fca569c48151fc57606f5ea7a/types/react/jsx-runtime.d.ts#L11) does.
> This is because the `React.JSX.IntrinsicAttributes` would be populated by `@lynx-js/types`, which contains incorrect properties.
fix: #871

fix(react/types): add `key` to `JSX.IntrinsicAttributes`

---

.changeset/cold-regions-attend.md
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-constants/src/types/MainThreadStartConfigs.ts
packages/web-platform/web-core-server/src/createLynxView.ts
packages/web-platform/web-core/src/uiThread/createRenderAllOnUI.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-mainthread-apis/src/MainThreadLynx.ts
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/elementAPI/elementCreating/elementCreatingFunctions.ts
packages/web-platform/web-mainthread-apis/src/index.ts
packages/web-platform/web-mainthread-apis/src/prepareMainThreadAPIs.ts
packages/web-platform/web-tests/shell-project/mainthread-test.ts
packages/web-platform/web-worker-runtime/src/index.ts
packages/web-platform/web-worker-runtime/src/mainThread/index.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts

rename many internal apis to make logic be clear:
multi-thread: startMainWorker -> prepareMainThreadAPIs -> startMainThread -> createMainThreadContext(new MainThreadRuntime)
all-on-ui: prepareMainThreadAPIs -> startMainThread -> createMainThreadContext(new MainThreadRuntime)

refactor: code clean

---

.changeset/fast-streets-learn.md
packages/webpack/template-webpack-plugin/etc/template-webpack-plugin.api.md
packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts
packages/webpack/template-webpack-plugin/test/cases/hooks/before-emit-filename-hash/webpack.config.js
packages/webpack/template-webpack-plugin/test/cases/hooks/before-emit-filename/webpack.config.js
packages/webpack/template-webpack-plugin/test/cases/hooks/before-emit-lepus/webpack.config.js
packages/webpack/template-webpack-plugin/test/cases/hooks/before-emit/webpack.config.js

feat: rename `lepus` to `mainThreadAssets` in `beforeEmit` hook

---

.changeset/long-paws-relax.md
packages/rspeedy/plugin-react/src/loaders.ts
packages/rspeedy/plugin-react/src/pluginReactLynx.ts
packages/rspeedy/plugin-react/src/validate.ts
packages/rspeedy/plugin-react/test/config.test.ts
packages/rspeedy/plugin-react/test/validate.test.ts

The `jsx` was marked as internal in #846, but it serves no purpose and should be removed entirely.
A minor bump has been made since removing an option is a breaking change.

fix(rspeedy/react)!: remove the `jsx` option

---

.changeset/solid-birds-vanish.md
packages/rspeedy/core/src/config/rsbuild/index.ts
packages/rspeedy/core/test/config/output/inline-scripts.test.ts
packages/rspeedy/core/test/config/rsbuild.test.ts

Fix a regression of #874.
We should set `output.inlineScripts` to Rsbuild, so that:
- The default value of `environment.config.output.inlineScripts` could be `true`
- The `output.inlineScripts` could be set in `lynx.config.js`

fix(rspeedy/core): `output.inlineScripts` should defaults to `true`

---

.changeset/icy-paths-battle.md
packages/webpack/chunk-loading-webpack-plugin/package.json

This is a cherry-pick of #921 to release/rspeedy-0-9-7.
Fix a regression of #798
PeerDependencies @rspack/core should be v1.3.10.

chore(webpack/chunk-loading): minor bump for updating peerDependencies @rspack/core

---

eslint.config.js

Update the copyright header template to use parentheses for the year placeholder and add a pattern to dynamically set the current year. This ensures the copyright year stays up-to-date automatically.

fix(eslint): update copyright header format and year pattern

---

eslint.config.js

Add 'preact' to the allowed modules list to resolve import errors when using the Preact library.

fix(eslint): allow preact imports in no-extraneous-import rule

---

examples/react/package.json
packages/react/package.json
packages/react/worklet-runtime/package.json
packages/rspeedy/create-rspeedy/template-react-ts/package.json
packages/rspeedy/create-rspeedy/template-react-vitest-rltl-ts/package.json
packages/rspeedy/upgrade-rspeedy/package.json
packages/third-party/tailwind-preset/package.json
pnpm-lock.yaml

Avoid TS error introduced in `@lynx-js/types` v3.3.1.
```
Error: src/App.tsx(41,24): error TS2322: Type 'number' is not assignable to type 'string'.
Error: Process completed with exit code 2.
```
> https://github.com/lynx-family/lynx-stack/actions/runs/15269327250/job/42941699971?pr=899

chore(deps): pin `@lynx-js/types` to v3.3.0

---

.changeset/busy-vans-heal.md
packages/web-platform/web-mainthread-apis/src/MainThreadRuntime.ts
packages/web-platform/web-mainthread-apis/src/utils/processStyleInfo.ts
packages/web-platform/web-tests/shell-project/web-core.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/config-mixed-01.config.ts
packages/web-platform/web-tests/tests/react/config-mixed-01/index.css
packages/web-platform/web-tests/tests/react/config-mixed-01/index.jsx

fix: style loss issue caused by incorrect handling of styleInfo-imports when enableCSSSelector and enableRemoveCSSScope are turned off.

fix(web): style loss when enableCSSSelector and enableRemoveCSSScope are turned off

---

.github/workflows/code-scanning.yml
.github/workflows/deploy-main.yml
.github/workflows/nodejs-dependencies.yml
.github/workflows/pull-request-content-check.yml
.github/workflows/relative-ci.yml
.github/workflows/rust.yml
.github/workflows/test.yml
.github/workflows/workflow-bench.yml
.github/workflows/workflow-build.yml
.github/workflows/workflow-bundle-analysis.yml
.github/workflows/workflow-test.yml
.github/workflows/workflow-website.yml

Set a `timeout-minutes` value for all jobs. The default of 360 minutes is too long for our needs. Adjusting this will prevent CI from hanging during network issues.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

ci: add `timeout-minutes` for all jobs

---

.github/workflows/workflow-bench.yml
.github/workflows/workflow-build.yml
.github/workflows/workflow-website.yml

Add a default permission to all jobs.
Fixes:
- https://github.com/lynx-family/lynx-stack/security/code-scanning/138
- https://github.com/lynx-family/lynx-stack/security/code-scanning/137
- https://github.com/lynx-family/lynx-stack/security/code-scanning/136
- https://github.com/lynx-family/lynx-stack/security/code-scanning/134

ci: add default permission

---

.github/workflows/workflow-build.yml

Previously, we restored the cache from the previous task of the current PR. However, GitHub runs actions not directly on the PR ref but on a ref merged with the `main` branch. As a result, using the cache from the current PR often leads to cache misses when there are changes in the `main` branch.
We would also save some time on saving the PR cache.

ci: not restore cache from same PR

---

.changeset/puny-monkeys-rule.md
packages/webpack/template-webpack-plugin/src/WebEncodePlugin.ts
packages/webpack/template-webpack-plugin/test/cases/web/page-config/a.js
packages/webpack/template-webpack-plugin/test/cases/web/page-config/b.js
packages/webpack/template-webpack-plugin/test/cases/web/page-config/rspack.config.js
packages/webpack/template-webpack-plugin/test/cases/web/page-config/test.config.cjs

feat: output pageConfig add a new source: `encodeOptions.sourceContent.config`.

feat(web): pageConfig add new source

---

.changeset/cool-nights-admire.md
packages/rspeedy/plugin-qrcode/package.json
packages/rspeedy/plugin-qrcode/src/shortcuts.ts
pnpm-lock.yaml

Reverts lynx-family/lynx-stack#902
We'll wait until https://github.com/bombshell-dev/clack/issues/331 and https://github.com/bombshell-dev/clack/issues/326 being released.

Revert "feat(rspeedy/qrcode): support autocomplete"

---

.changeset/fresh-guests-wish.md
packages/react/transform/src/swc_plugin_worklet/mod.rs
packages/react/transform/src/swc_plugin_worklet/worklet_type.rs
packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_worklet/mod.rs/should_transform_lepus_alias.js

Support the 'main-thread' directive as an alias for 'main thread'.
This change would provide a better experience when using AI tools to generate code automatically.

feat(react/runtime): support 'main-thread' as an alias for 'main thread'

---

.changeset/curly-trams-notice.md
packages/web-platform/web-constants/src/types/PageConfig.ts
packages/web-platform/web-mainthread-apis/src/prepareMainThreadAPIs.ts

feat: add new pageConfig configuration: enableJSDataProcessor

feat(web): add new pageConfig configuration: enableJSDataProcessor

---

.changeset/busy-dingos-shake.md
packages/web-platform/web-elements/src/XInput/XInput.ts
packages/web-platform/web-elements/src/XInput/XInputEvents.ts
packages/web-platform/web-elements/src/XTextarea/XTextarea.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/basic-element-x-input-getValue/index.jsx
packages/web-platform/web-tests/tests/react/basic-element-x-textarea-getValue/index.jsx

feat: x-input && x-textarea add new method: `getValue`, which returns the value of the input element, selectionStart and selectEnd when success.

feat(web): x-input && x-textarea add new method: getValue

---

.changeset/chilly-snakes-hunt.md
packages/web-platform/web-elements/src/XInput/XInputEvents.ts
packages/web-platform/web-elements/src/XTextarea/XTextareaEvents.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/basic-element-x-input-bindinput/index.jsx

feat: x-input and x-textarea bindinput event return structures add `selectionStart`, `selectionEnd`, and `textLength`, `textLength` are marked as @deprecated

feat(web): x-input and x-textarea bindinput event structure change

---

packages/react/transform/__test__/fixture.spec.js

Esbuild uses differnt icons on Windows to avoid crash.
See: https://github.com/evanw/esbuild/blob/f4159a7b823cd5fe2217da2c30e8873d2f319667/internal/logger/logger.go#L82.
We should update the snapshot to make test work on Windows.

test(react/transform): use different icon on Windows

---

website/rspress.config.ts

As we are using custom domain, the `base` is no longer needed.

docs: remove unused `base`

---

packages/web-platform/web-tests/package.json

Make `@lynx-js/web-tests#build` work on Windows.
issue: #81

chore(web-tests): use cross platform build command

---

packages/rspeedy/core/test/cli/register.test.ts
packages/rspeedy/core/test/config/loadConfig.test.ts
packages/rspeedy/core/test/plugins/dev.plugin.test.ts
packages/rspeedy/plugin-react-alias/test/index.test.ts
packages/rspeedy/plugin-react/test/background-only.test.ts
packages/rspeedy/plugin-react/test/basic.test.ts
packages/rspeedy/plugin-react/test/config.test.ts
packages/rspeedy/plugin-react/test/css.test.ts
packages/rspeedy/plugin-react/test/lazy.test.ts
packages/rspeedy/plugin-react/test/swc-config.test.ts

Make most part of the Rspeedy unit tests working on Windows. Including:
1. Use `.replaceAll('/', sep)` for all alias like `'@rspack/core/hot/emitter.js'`.
2. Use `[\\/]` instead of `\/` in RegExp.
3. Remove `source.tsConfig` since it uses `new URL` which not working on Windows.
issue: #81

test(rspeedy): fix tests on Windows

---

.github/workflows/workflow-bench.yml
.github/workflows/workflow-build.yml
.github/workflows/workflow-bundle-analysis.yml
.github/workflows/workflow-test.yml
.github/workflows/workflow-website.yml

This is the first step to construct Windows CI. Enable build on Windows.
1. Use matrix for `workflow-build.yml`. Re-use the existing build workflow.
2. Switch to cache key v4 to include `${{ runner.os }}`.
issue: #81

ci: enable build on Windows

---

.github/workflows/rust.yml

Following up #1030. Enable Rust test on Windows.
1. Use matrix to reuse existing workflow.
2. Set `timeout-minutes: 30` since Rust toolchain downloading and compiling could be slow.
3. Set `cache: false` for `rustfmt` job since we don't need to compile in this job.
issue: #81

ci: enable Rust test on Windows

---

.changeset/tired-breads-wonder.md
packages/react/testing-library/src/__tests__/css.test.jsx
packages/react/testing-library/src/__tests__/worklet.test.jsx
packages/rspeedy/create-rspeedy/template-react-vitest-rltl-js/src/__tests__/index.test.jsx
packages/rspeedy/create-rspeedy/template-react-vitest-rltl-ts/src/__tests__/index.test.tsx
packages/testing-library/testing-environment/src/lynx/ElementPAPI.ts

In JSDOM, `element.style.cssText = 'flex:1'` will normalize the style to `flex: 1 1 0%;`, this is not the  actual behavior of `__SetInlineStyles` in Lynx. We changed to use `element.setAttributeNS(null, 'style', 'flex:1');` to avoid issues.
Related change in `cssstyle`: https://github.com/jsdom/cssstyle/commit/79c88c407ee5da7f4fd9849725c9e9cc04b1a2c8#diff-72d4401db3e024bcef1fc57d7d43457be6f5b3f8f89a80b1580063362e280782

fix(testing-library): __SetInlineStyles of raw styles should not normalize css

---

packages/react/transform/src/swc_plugin_compat/is_component_class.rs
packages/react/transform/turbo.json

Currently, we do not need `build:debug` on CI. And there are cases that Build (Windows) failed to exit when building failed. https://github.com/lynx-family/lynx-stack/actions/runs/15530223050/job/43718863465?pr=770.
So we are removing it from `react/transform/turbo.json`.

chore(react/transform): remove `build:debug` from `turbo build`

---

.github/workflows/rust.yml

Partially reverting #1031 due to frequent timeout issues with Windows Rust tests.

ci: disable Rust test on Windows

---

.changeset/light-wombats-buy.md
packages/webpack/react-webpack-plugin/src/loaders/options.ts

Currently, we use `__snapshot_${hash(filename)}_${hash(content)}` as snapshot ID. However, the filename is not normalized and it's different between Linux/macOS and Windows.
To make Web SSR snapshot tests work, we need to generate the same snapshot ID on different platform.
issue: #81

fix(webpack/react): always use posix filename for snapshot ID

---

.changeset/shy-needles-count.md
packages/web-platform/web-elements-template/src/index.ts

https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img#loading

perf: add loading="lazy" for image element

---

.changeset/red-meals-battle.md
packages/react/runtime/__test__/snapshot/workletRef.test.jsx
packages/react/runtime/__test__/worklet/workletRef.test.jsx
packages/react/runtime/src/lifecycle/patch/updateMainThread.ts
packages/react/runtime/src/lifecycle/reload.ts
packages/react/runtime/src/list.ts
packages/react/runtime/src/lynx/calledByNative.ts
packages/react/runtime/src/snapshot/workletRef.ts
packages/react/worklet-runtime/__test__/workletRef.test.js
packages/react/worklet-runtime/src/bindings/observers.ts
packages/react/worklet-runtime/src/hydrate.ts

Fix a problem causing `MainThreadRef`s to not be updated correctly during hydration when they are set to `main-thread:ref`s.
This is caused by a mixed order of MTS hydration and `main-thread:ref` triggering. Therefore, we ensure that hydration completes first before triggering references.
Fix #1046

fix(react/runtime): delay applying mt:ref until hydration has finished

---

.changeset/tired-clowns-flash.md
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-constants/src/types/BackThreadStartConfigs.ts
packages/web-platform/web-constants/src/types/Cloneable.ts
packages/web-platform/web-constants/src/types/I18n.ts
packages/web-platform/web-core-server/src/createLynxView.ts
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/apis/createLynxView.ts
packages/web-platform/web-core/src/uiThread/createRenderAllOnUI.ts
packages/web-platform/web-core/src/uiThread/createRenderMultiThread.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-mainthread-apis/src/prepareMainThreadAPIs.ts
packages/web-platform/web-tests/tests/web-core.test.ts
packages/web-platform/web-worker-runtime/src/mainThread/startMainThread.ts

feat: add `updateI18nResources` method of lynx-view.
Now you can use `updateI18nResources` to update i18nResources, and then use _I18nResourceTranslation() to get the updated result.

feat(web): add updateI18nResources method of lynx-view

---

.changeset/hip-jars-report.md
packages/react/runtime/__test__/snapshotPatch.test.jsx
packages/react/runtime/src/snapshot.ts

Add explicit error handling when snapshot definition is not found to provide clearer debugging information.

fix(react): improve error message for missing snapshots

---

.changeset/legal-women-kneel.md
.github/workflows/test.yml
packages/rspeedy/create-rspeedy/package.json
packages/rspeedy/create-rspeedy/template-react-ts/lynx.config.ts
packages/rspeedy/create-rspeedy/template-react-ts/package.json
packages/rspeedy/create-rspeedy/template-react-vitest-rltl-ts/lynx.config.ts
packages/rspeedy/create-rspeedy/template-react-vitest-rltl-ts/package.json
pnpm-lock.yaml

Enable TypeScript check by default.
close: #1063

feat(create-rspeedy): integrate with `@rsbuild/plugin-type-check`

---

.changeset/empty-roses-greet.md
packages/react/runtime/__test__/list.test.jsx
packages/react/runtime/__test__/renderToOpcodes.test.jsx
packages/react/runtime/src/backgroundSnapshot.ts
packages/react/runtime/src/list.ts
packages/react/runtime/src/snapshot.ts
packages/react/testing-library/src/__tests__/list.test.jsx

Different from #1054, this fix avoids disconnecting the `SnapshotInstance` that is about to be reused, and avoids incompleteness when it is reused in the `<list/>`.

fix(react): memory leak because of cycle reference

---

.changeset/gold-goats-remain.md
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-tests/tests/react.spec.ts

fix: lynx-view `updateGlobalProps` method will also update globalProps, so `reload()` will use the latest updated globalProps.
#1112

fix(web): updateGlobalProps will update globalProps also

---

.changeset/violet-horses-march.md
packages/web-platform/web-mainthread-apis/src/utils/decodeCssInJs.ts
packages/web-platform/web-tests/resources/web-core.enable-css-selector-false.json
packages/web-platform/web-tests/shell-project/web-core.ts
packages/web-platform/web-tests/tests/web-core.test.ts

fix: `decodeCssInJs` will not throw error.
Before this pr, decoding css will be strictly executed according to cssInfo, and an error will be thrown if data that does not meet the requirements is encountered. Now it is changed to console.warn, which will not block rendering.

fix(web): decodeCssInJs will not throw an error

---

.changeset/forty-jars-scream.md
packages/web-platform/web-constants/src/endpoints.ts
packages/web-platform/web-constants/src/types/MainThreadGlobalThis.ts
packages/web-platform/web-core-server/src/utils/loadTemplate.ts
packages/web-platform/web-core/src/apis/LynxView.ts
packages/web-platform/web-core/src/uiThread/createRenderAllOnUI.ts
packages/web-platform/web-core/src/uiThread/createRenderMultiThread.ts
packages/web-platform/web-core/src/uiThread/crossThreadHandlers/registerReportErrorHandler.ts
packages/web-platform/web-core/src/uiThread/startUIThread.ts
packages/web-platform/web-core/src/utils/loadTemplate.ts
packages/web-platform/web-mainthread-apis/src/createMainThreadGlobalThis.ts
packages/web-platform/web-tests/shell-project/mainthread-test.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/api-set-release/index.jsx

feat: add `_SetSourceMapRelease(errInfo)` MTS API.
You can get `errInfo.release` through `e.detail.release` in the error event callback of lynx-view.
The `_SetSourceMapRelease` function is not complete yet, because it is currently limited by the Web platform and some functions and some props such as `err.stack` do not need to be supported for the time being.

feat(web): add _SetSourceMapRelease(errInfo) MTS API.

---

.github/workflows/deploy-main.yml
.github/workflows/test.yml
CONTRIBUTING.md

Vitest docs: https://vitest.dev/guide/cli.html#testtimeout

ci: use `--testTimeout` instead of `--test-timeout`

---

.changeset/brave-cobras-hide.md
packages/react/testing-library/src/__tests__/end-to-end.test.jsx
packages/react/testing-library/src/__tests__/lazy-bundle/index.test.jsx
packages/testing-library/testing-environment/src/index.ts

Fix the unhandled rejection on Windows ("lynx.getJSContext is not a function").
The `lynx.getJSContext` does exist on BTS, so does `lynx.getCoreContext` on MTS.

fix(testing-library): fix flaky Windows tests

---

.github/workflows/workflow-build.yml
packages/web-platform/web-tests/package.json
turbo.json

1. Increase max-old-space-size to avoid OOM in build
2. Remove "|| echo 'Skipping build:cases in non-CI environment'" as it causes the build to be marked as successful even when it fails.
https://github.com/lynx-family/lynx-stack/actions/runs/15816546524/job/44576625549?pr=1129

ci: avoid OOM on Windows build

---

.changeset/better-wings-peel.md
packages/web-platform/web-constants/src/types/NativeApp.ts
packages/web-platform/web-core/src/uiThread/startBackground.ts
packages/web-platform/web-tests/shell-project/index.ts
packages/web-platform/web-tests/shell-project/lynx-view.ts
packages/web-platform/web-tests/tests/react.spec.ts
packages/web-platform/web-tests/tests/react/api-report-error/index.jsx
packages/web-platform/web-tests/tests/react/api-set-release-bts/index.jsx
packages/web-platform/web-worker-runtime/src/backgroundThread/background-apis/createNativeApp.ts

feat: support BTS API `lynx.reportError` && `__SetSourceMapRelease`, now you can use it and handle it in lynx-view error event.

feat(web): support lynx.reportError and __SetSourceMapRelease

---

.changeset/many-nails-press.md
packages/web-platform/web-constants/src/eventName.ts
packages/web-platform/web-elements/src/XInput/XInputEvents.ts
packages/web-platform/web-elements/src/XTextarea/XTextareaEvents.ts
packages/web-platform/web-tests/tests/react/basic-element-x-input-bindinput/index.jsx
packages/web-platform/web-tests/tests/react/basic-element-x-textarea-bindinput/index.jsx
packages/web-platform/web-tests/tests/web-elements.spec.ts
packages/web-platform/web-tests/tests/web-elements/x-textarea/event-input.html

#1174 
fix #1024
fix: in lynx-view all-on-ui mode, the input event of input and textarea is triggered twice, and the first e.detail is a string, which does not conform to the expected data format.

fix(web): input event trigger twice && detail.value miss

---

.changeset/fifty-rats-tickle.md
.changeset/loose-zoos-say.md
packages/rspeedy/plugin-react/src/pluginReactLynx.ts
packages/rspeedy/plugin-react/test/config.test.ts
packages/webpack/runtime-wrapper-webpack-plugin/src/RuntimeWrapperWebpackPlugin.ts
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-false/fetch.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-false/index.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-false/rspack.config.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-false/webpack.config.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-true/fetch.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-true/index.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-true/rspack.config.js
packages/webpack/runtime-wrapper-webpack-plugin/test/cases/variables/iife-true/webpack.config.js

Fix memory leak when using `<list />` by removing the IIFE wrapper in `main-thread.js`.
Maybe we should set `output.iife: false` in `@lynx-js/rspeedy`.

fix(rspeedy/react): fix memory leak when using `<list />`

---

.changeset/proud-maps-drive.md
packages/react/runtime/__test__/lynx/lazy-bundle.test.js
packages/react/runtime/src/lynx/lazy-bundle.ts
packages/react/runtime/vitest.config.ts

Make lazy bundle being able to resolve and rendered on the first screen of background thread.
The `QueryComponent` API can support both blocking and non-blocking returns.
**Before this patch**:
- main-thread: Directly render the children of `<Suspense />`, which resolves to the content of the lazy bundle.
- background: Firstly render to the children of `<Suspense />`, which throw an error. Then the promise of `loadLazyBundle` resolves, which makes `<Suspense />` updates to render the content of the lazy bundle.
The render result would be:
Full content -> blank -> full content
which is quite weird for end-user.
**After this patch**:
Both main-thread and background would directly render the children of `<Suspense />`, which resolves to the content of the lazy bundle.

fix(react/runtime): make `loadLazyBundle` return sync `then`

---

.changeset/young-doodles-strive.md
packages/web-platform/web-constants/src/utils/generateTemplate.ts
packages/web-platform/web-constants/src/utils/index.ts
packages/web-platform/web-core-server/src/utils/loadTemplate.ts
packages/web-platform/web-core/src/utils/loadTemplate.ts

chore: extract shared logic from web-core and web-core-server's loadTemplate into a unified generateTemplate function

chore(web): extract shared logic of loadTemplate

---

.changeset/major-drinks-lead.md
packages/third-party/tailwind-preset/turbo.json

Fix missing `dist/` in published `@lynx-js/tailwind-preset` v0.1.0.

chore(tailwind-preset): add missing `turbo.json`

---

.changeset/grumpy-owls-argue.md
packages/react/runtime/__test__/debug/children-with-same-key.test.jsx
packages/react/runtime/__test__/debug/hooks-in-render.test.jsx
packages/react/runtime/__test__/debug/hooks-invalid-args.test.jsx
packages/react/runtime/__test__/debug/jsx-twice.test.jsx
packages/react/runtime/__test__/debug/missing-suspense.test.jsx
packages/react/runtime/__test__/debug/object-as-child.test.jsx
packages/react/runtime/__test__/debug/set-state-in-ctor.test.jsx
packages/react/runtime/__test__/debug/too-many-rerenders.test.jsx
packages/react/runtime/__test__/debug/undefined-component.test.jsx
packages/react/runtime/__test__/utils/setup.js
packages/react/runtime/src/root.ts

This patch add a `nodeType` property for `root` which make `@lynx-js/react` work with `preact/debug`.
Corresponding tests for supported `preact/debug` checks have been added.
> [!NOTE]
> The tests are divided into separate files because `preact/debug` stores the component stack in memory, which could lead to incorrect behavior if the initial render fails.
fix: m-6732088176

feat(react/runtime): integrate with `preact/debug`

---

.changeset/evil-pigs-doubt.md
packages/rspeedy/core/etc/rspeedy.api.md
packages/rspeedy/core/src/config/rsbuild/index.ts
packages/rspeedy/core/src/config/server/index.ts
packages/rspeedy/core/test/config/rsbuild.test.ts
packages/rspeedy/core/test/config/server.test-d.ts

https://github.com/lynx-family/lynx-stack/issues/1691
@coderabbitai summary

feat(rspeedy): Support `server.compress`
