lynx-family/lynx-stack

.github/workflows/deploy-main.yml
Resolve the [CI publishing failure](https://github.com/lynx-family/lynx-stack/actions/runs/13653137974/job/38166378353).
=> ci: add `id-token: write` for npm provenance

.changeset/config.json, package.json, pnpm-lock.yaml
Generating `CHANGELOG.md` using `@svitejs/changesets-changelog-github-compact`(which is used by [svelte](https://github.com/sveltejs/svelte))
Example:
=> chore(changeset): use GitHub changelog

.github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
=> fix(workflow): feature request template

.changeset/grumpy-hairs-retire.md, packages/webpack/template-webpack-plugin/etc/template-webpack-plugin.api.md, packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts, packages/webpack/template-webpack-plugin/test/__snapshots__/cases.test.ts.snap
=> feat(template-webpack-plugin): add `defaultOverflowVisible` plugin option

.github/ISSUE_TEMPLATE/config.yml
=> chore(workflow): add issue template config

.changeset/true-clubs-shout.md, packages/rspeedy/create-rspeedy/template-react-js/src/index.js
`cd rspeedy`
`cd create-rspeedy`
`cd template-react-js`
`cd src`
`Rename index.jsx to index.js`
`Open index.js`
`Change import statement in index.js from `App.js` to `App.jsx``
** These are the ONLY changes made to the `rspeedy` package within `template-react-js/src`.**
TEST PASSED. Changeset included. 
When starting a new project with the JavaScript template on Linux, users encounter a critical "Module not found" error that prevents the development server from starting.
I spent a few hours messing around with configs and then I took a careful look at the error. I realized that rspeedy was expecting an index.js file and no matter how I changed the config (even to include an `aliasExtension` to take in a `.jsx` file or `.tsx` file it would have no effect on using `npm run dev`.
From here I …
=> fix(create-rspeedy): "Module Not Found" index.js

packages/react/README.md, packages/rspeedy/core/README.md, packages/rspeedy/create-rspeedy/README.md, packages/rspeedy/plugin-qrcode/README.md, packages/rspeedy/plugin-react/README.md
All the assets on the website are moved to the CDN. Update the banner image, too.
=> chore: update the banner image in README

.changeset/fuzzy-carrots-remain.md, packages/webpack/template-webpack-plugin/src/LynxEncodePlugin.ts
=> fix(webpack/template): use `getEncodeMode` instead of `encode`

codecov.yml, vitest.config.ts
1. Use [Components](https://docs.codecov.com/docs/components) for different projects.
2. Ignore some non-source code paths from coverage reports.
=> ci(codecov): update coverage settings

.changeset/eighty-penguins-move.md, packages/react/transform/src/css_property.rs
Add two new css properties: offset-path and offset-distance for compile.
=> chore: add new css properties: offset-path, offset-distance

.changeset/funny-jokes-march.md, packages/react/runtime/__test__/preact.test.jsx, packages/react/runtime/src/internal.ts, packages/react/runtime/src/lynx.ts, packages/react/runtime/src/lynx/tt.ts
=> fix(react/runtime): make `setupLynxEnv` run earlier

.changeset/public-flies-leave.md, packages/webpack/webpack-dev-transport/package.json
It's aim to customize the main-thread HMR and it is only experimental now.
=> feat(dev-transport): export `reloadApp` module

packages/web-platform/web-explorer/rsbuild.config.ts
=> chore: generate stat.json while building web-explorer

.github/workflows/pre-code-review-check.yml, .github/workflows/rust.yml, .github/workflows/test.yml, .github/workflows/workflow-test.yml
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
=> ci: remove tj-actions/changed-files action

.changeset/happy-hairs-nail.md, .changeset/some-ducks-dig.md, packages/react/runtime/__test__/lifecycle.test.jsx, packages/react/runtime/__test__/lynx/timing.test.jsx, packages/react/runtime/__test__/snapshot/gesture.test.jsx, packages/react/runtime/__test__/snapshot/ref.test.jsx, packages/react/runtime/__test__/snapshot/workletEvent.test.jsx, packages/react/runtime/__test__/snapshot/workletRef.test.jsx, packages/react/runtime/__test__/worklet/workletRef.test.jsx, packages/react/runtime/src/lifecycle/destroy.ts, packages/react/runtime/src/lifecycle/patch/commit.ts, packages/react/runtime/src/lifecycle/reload.ts, packages/react/runtime/src/lifecycle/render.ts, packages/react/runtime/src/lynx-api.ts, packages/react/runtime/src/lynx/tt.ts, packages/react/runtime/types/internal-preact.d.ts, packages/rspeedy/plugin-react/package.json, packages/webpack/react-webpack-plugin/package.json
This PR enhances the React runtime by implementing a batching mechanism that accumulates multiple patch updates and sends them to the main thread in a single render pass. This optimization reduces redundant layout operations, improves rendering performance, and prevents screen flickering.
- **Implemented batch rendering**: Added batching mechanism to accumulate patches and send them together in one render cycle
- **Optimized commit process**: Modified the commit hook to postpone sending updates until all patches are ready
- **Added patch accumulation**: Created a storage array and functions to collect multiple patches before committing
- **Timing API changes**: Adjusted the timing events to fire once per render cycle instead of for each individual update
- **Refactored render functions**: …
=> fix(react/runtime): batch multiple patches for main thread communication

.github/workflows/deploy-main.yml, .github/workflows/stale.yml
Add `if: github.repository == 'lynx-family/lynx-stack'` to deploy tasks so that these would not run in a forked repo.
=> ci: avoid workflows run on forks

.changeset/flat-llamas-start.md, packages/web-platform/web-core/src/apis/LynxView.ts, packages/web-platform/web-core/src/apis/createLynxView.ts, packages/web-platform/web-core/src/uiThread/crossThreadHandlers/registerFlushElementTreeHandler.ts, packages/web-platform/web-core/src/uiThread/startUIThread.ts
remove duplicated overrideLynxTagToHTMLTagMap
=> refactor: code clean

.github/workflows/test.yml, codecov.yml
See: https://docs.codecov.com/docs/fixing-paths
=> ci(codecov): try to fix paths uploaded by test-react

.github/renovate.json5, pnpm-lock.yaml, website/package.json, website/rspress.config.ts
1. Add `base: '/lynx-stack/`
1. Group API Extractor related packages
1. Ignore API documentor updates until Rspress fix the table issue
1. Bump @microsoft/api-extractor-model
=> docs: fix website not working

.github/actions/setup-playwright/action.yml, .github/workflows/test.yml, .github/workflows/workflow-test.yml
1. Remove `apt install` in test-rspeedy
1. Add a playwright cache action
=> ci: speed up CI

.github/workflows/test.yml, packages/tools/css-serializer/vitest.config.ts
The tests for `tools/css-serializer` were previously not running. This patch ensures the tests are now executed in the CI pipeline.
=> test: add `packages/tools` to CI

.github/workflows/deploy-main.yml, .github/workflows/test.yml, .github/workflows/workflow-test.yml
Add `github` and `junit` reporter to playwright.
Also, run the test in `deploy-main.yml` so that
1. We get a test report of playwright on each commit of `main`. We can see flaky tests in https://app.codecov.io/gh/lynx-family/lynx-stack/tests/main
2. The cache in setup-playwright can be used by other PRs.
=> ci: enable playwright test report

packages/rspeedy/core/README.md, packages/rspeedy/plugin-qrcode/README.md, packages/rspeedy/plugin-react/README.md
The link to CONTRIBUTING.md was broken
I noticed this when I was trying to fix rspeedy.
=> docs: Correct case for CONTRIBUTING.md link

.changeset/every-clubs-ring.md, packages/rspeedy/core/etc/rspeedy.api.md, packages/rspeedy/core/src/config/rsbuild/index.ts, packages/rspeedy/core/src/config/server/index.ts, packages/rspeedy/core/test/config/server.test-d.ts
close https://github.com/lynx-family/lynx-stack/issues/294
=> feat(rspeedy): Support server.strictPort

.changeset/blue-taxis-make.md, packages/rspeedy/core/etc/rspeedy.api.md, packages/rspeedy/core/src/config/dev/index.ts, packages/rspeedy/core/src/config/rsbuild/index.ts, packages/rspeedy/core/test/config/dev.test-d.ts, packages/rspeedy/core/test/config/rsbuild.test.ts, packages/rspeedy/core/test/config/validate.test.ts
close https://github.com/lynx-family/lynx-stack/issues/297
=> feat(rspeedy): Support dev.progressBar

.github/workflows/deploy-main.yml, .github/workflows/test.yml, .github/workflows/workflow-test.yml, codecov.yml, packages/web-platform/web-tests/tests/coverage-fixture.ts, packages/web-platform/web-tests/tests/main-thread-apis.test.ts, packages/web-platform/web-tests/tests/performance.test.ts, packages/web-platform/web-tests/tests/react.spec.ts, packages/web-platform/web-tests/tests/rpc.spec.ts, packages/web-platform/web-tests/tests/web-core.test.ts, packages/web-platform/web-tests/tests/web-elements.spec.ts
=> test: enable coverage for playwright

.changeset/chilly-cougars-throw.md, packages/web-platform/web-elements-reactive/src/component.ts
Create template of web component when used #285
=> perf(web): Create template of web component when used

.github/actions/setup-playwright/action.yml, packages/web-platform/web-tests/tests/react.spec.ts
=> ci: fix setup-playwright

.changeset/shy-papayas-itch.md, packages/rspeedy/upgrade-rspeedy/package.json, pnpm-lock.yaml
Allow upgrading Web-related packages with `upgrade-rspeedy`.
=> feat(upgrade-rspeedy): add web-related packages

.changeset/lucky-radios-shake.md, packages/react/runtime/src/lifecycle/patch/commit.ts
fix: https://github.com/lynx-family/lynx/issues/474
=> fix(react/runtime): fix stack underflow issue when running on PrimJS

.github/workflows/deploy-main.yml, .github/workflows/test.yml, .github/workflows/workflow-build.yml, .github/workflows/workflow-test.yml, codecov.yml, packages/web-platform/web-explorer/package.json, packages/web-platform/web-explorer/rsbuild.config.ts, packages/web-platform/web-explorer/turbo.json, pnpm-lock.yaml
The web-explorer includes all essential package for web platform. It's perfect for analyzing bundle size.
=> ci(web): add bunele size analysis for web-explorer

packages/web-platform/web-core/README.md, packages/web-platform/web-elements/README.md
chore(web): update new usage of web-elements and web-core
=> chore(web): update new usage of web-elements and web-core

.github/actions/setup-playwright/action.yml, .github/workflows/workflow-bench.yml, .github/workflows/workflow-build.yml, .github/workflows/workflow-test.yml, .github/workflows/workflow-website.yml, cspell.jsonc
Before
https://github.com/lynx-family/lynx-stack/actions/runs/14099480308/job/39492937713?pr=353
After
=> ci: improve cache performance

.github/workflows/test.yml
=> ci: add type check

.changeset/rotten-pigs-wash.md, packages/web-platform/web-core/src/uiThread/bootWorkers.ts
the bundle size will be optimized about 28.2KB
=> fix(web): rsbuild will bundle 2 exactly same chunk for two same `new Worker` stmt

.changeset/sad-shirts-reply.md, packages/web-platform/web-constants/src/types/NapiModules.ts, packages/web-platform/web-core/src/apis/LynxView.ts, packages/web-platform/web-tests/shell-project/web-core.ts, packages/web-platform/web-tests/tests/web-core.test.ts, packages/web-platform/web-worker-rpc/src/Rpc.ts
feat: The onNapiModulesCall function of lynx-view provides the fourth parameter: `lynxView`, which is the actual lynx-view DOM.
=> feat(web): The onNapiModulesCall function add lynxView parameter

.changeset/two-masks-decide.md, packages/web-platform/web-constants/src/endpoints.ts, packages/web-platform/web-mainthread-apis/src/elementAPI/event/eventFunctions.ts, packages/web-platform/web-tests/shell-project/mainthread-test.ts, packages/web-platform/web-tests/tests/main-thread-apis.test.ts
=> fix: publicComponentEvent args order

.changeset/kind-cloths-clap.md, packages/rspeedy/plugin-react/etc/react-rsbuild-plugin.api.md, packages/rspeedy/plugin-react/src/entry.ts, packages/rspeedy/plugin-react/src/pluginReactLynx.ts, packages/webpack/react-webpack-plugin/etc/react-webpack-plugin.api.md, packages/webpack/react-webpack-plugin/src/ReactWebpackPlugin.ts, packages/webpack/react-webpack-plugin/src/index.ts
=> feat: add extractStr option to pluginReactLynx

packages/rspeedy/core/test/plugins/dev.plugin.test.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Reverts lynx-family/lynx-stack#382
=> Revert "chore(deps): update rspack monorepo to v1.3.0"

.changeset/odd-icons-run.md
https://github.com/lynx-family/lynx-stack/pull/343 does not need to publish tailwind-preset.
=> chore: remove wrong changeset

.changeset/violet-days-beam.md, packages/rspeedy/plugin-react/src/generator.ts, packages/rspeedy/plugin-react/src/pluginReactLynx.ts, packages/rspeedy/plugin-react/test/generator.test.ts
Related [issue](https://github.com/webpack/webpack/issues/19319)
=> feat(plugin-react): disable `module.generator.json.JSONParse` option

packages/rspeedy/core/test/plugins/dev.plugin.test.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Reverts lynx-family/lynx-stack#407
Reapply lynx-family/lynx-stack#382
=> chore(deps): reapply "chore(deps): update rspack monorepo to v1.3.0"

packages/webpack/chunk-loading-webpack-plugin/package.json, pnpm-lock.yaml
=> chore: remove unused rspack/cli

.changeset/icy-parrots-stare.md, packages/react/runtime/__test__/ssr.test.jsx, packages/react/runtime/src/lynx/calledByNative.ts, packages/react/runtime/src/snapshot.ts
=> fix(react/runtime): do some global var initialize in hydrate

.github/workflows/test.yml, codecov.yml
=> ci(codecov): enable project coverage

.github/renovate.json5
- `renovate` -> `bot:renovate`
- `Rspack` -> `upstream:rspack`
- `Rsbuild` -> `upstream:rspack`
- ~~`peerDependencies`~~
=> chore: update renovate labels

.changeset/fine-turtles-strive.md, packages/web-platform/web-elements/tsconfig.json
=> chore: bump the output target to es2024

.github/renovate.json5
https://www.npmjs.com/package/typia-rspack-plugin
close: #539
=> chore(renovate): use correct typia plugin name

.github/workflows/test.yml, cspell.jsonc
See https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
=> ci: integrate with zizmor

.changeset/pretty-coats-bet.md, packages/web-platform/web-elements/src/XAudioTT/XAudioTT.ts
fix: add mode: no-cors of fetch in x-audio-tt
=> fix(web): add mode: no-cors of fetch in x-audio-tt

.changeset/pretty-coats-bet.md, packages/web-platform/web-elements/src/XAudioTT/XAudioTT.ts
Reverts lynx-family/lynx-stack#586
=> Revert "fix(web): add mode: no-cors of fetch in x-audio-tt"

packages/web-platform/web-tests/tests/performance.test.ts
x-list-waterfall-1000 LayoutCount is actually close to 1000
=> chore(web): x-list-waterfall-1000 flaky

.changeset/yellow-wasps-brush.md, packages/rspeedy/plugin-qrcode/src/index.ts, packages/rspeedy/plugin-qrcode/test/fixtures/error/index.js, packages/rspeedy/plugin-qrcode/test/index.test.ts
=> fix(qrcode-plugin): QR code fails to print after initial compilation errors are fixed

.changeset/tangy-dancers-jam.md, packages/react/transform/src/swc_plugin_snapshot/mod.rs, packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_snapshot/mod.rs/should_excape_newline_character.js
=> fix(react/transform): "Unterminated string constant" when multi-line JSX StringLiteral

.changeset/eight-swans-mix.md, packages/web-platform/web-explorer/index.html, packages/web-platform/web-explorer/preinstalled/vant-touch.js
https://github.com/youzan/vant/issues/13464
=> fix: fork @vant/touch-emulator and make it work with shadowroot

.changeset/tall-spiders-punch.md, packages/react/runtime/__test__/lynx/timing.test.jsx, packages/react/runtime/__test__/utils/globals.js, packages/react/runtime/src/lynx/performance.ts, packages/react/runtime/types/types.d.ts
Resolved a compatibility problem caused by break changes in the _onPipelineStart method signature. For engine versions 3.1 and above, adjusted the method call to include PipelineOptions as an argument.
issue: #659
=> fix(timing): Fix Compatibility Issue in _onPipelineStart

.github/workflows/deploy-main.yml
Allow release on `release/*` branch.
=> ci: setup deploy on release branch

.changeset/tall-spiders-punch.md, .github/workflows/deploy-main.yml, packages/react/CHANGELOG.md, packages/react/package.json
This PR cherry-pick the `release/react-0-107-x` branch to `main`. Including:
- #670 
- #671 
- #673
=> chore: cherry-pick release/react-0-107-x

Cargo.lock, packages/react/transform/Cargo.toml, packages/react/transform/src/bundle.rs, packages/react/transform/src/esbuild.rs, packages/react/transform/src/lib.rs
See:
- Rspack: https://github.com/web-infra-dev/rspack/pull/10256
- Breaking changes:
- `source_map_url`: https://github.com/swc-project/swc/pull/10346
- `&mut DiagnosticBuilder<'_>`: https://github.com/swc-project/swc/pull/10241
=> fix(deps): bump swc_core v22.5.3

packages/web-platform/web-tests/package.json, pnpm-lock.yaml
The `@lhci/cli` package is exclusively utilized in CI environments. This update eliminates it from `package.json` to expedite installation time.
=> chore: avoid installing `@lhci/cli`

.github/renovate.json5
We should pin the GitHub Actions to digest. See: https://github.com/lynx-family/lynx-stack/security/code-scanning/39
=> chore(renovate): pin github-action digest

.github/workflows/deploy-main.yml, .github/workflows/relative-ci.yml, .github/workflows/rust.yml
It seems like the `workflow_run` event is not triggered when using `workflow_call`.
=> ci: change workflow name

.github/workflows/relative-ci.yml
We accidentally removed "Deploy" and "Test" in #743. :)
=> ci: fix workflow_run

.changeset/nice-needles-press.md, packages/rspeedy/core/CHANGELOG.md, packages/rspeedy/core/src/cli/commands.ts, packages/rspeedy/core/src/cli/init.ts, packages/rspeedy/core/src/cli/inspect.ts, packages/rspeedy/core/test/cli/build.test.ts, packages/rspeedy/core/test/cli/inspect.test.ts, website/docs/en/guide/cli.md, website/docs/zh/guide/cli.md
issue: https://github.com/lynx-family/lynx-stack/issues/304
=> feat(rspeedy/cli): support `--mode`

.github/codeql-config.yml, .github/workflows/code-scanning.yml, .github/workflows/codeql.yml, .github/workflows/test.yml
This patch setup the Advanced CodeQL code scanning.
See:
- https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/configuring-advanced-setup-for-code-scanning
- https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
=> ci: integrate with CodeQL

.changeset/lucky-socks-play.md, packages/rspeedy/core/etc/rspeedy.api.md, packages/rspeedy/core/src/cli/init.ts, packages/rspeedy/core/src/config/performance/build-cache.ts, packages/rspeedy/core/src/config/performance/index.ts, packages/rspeedy/core/src/config/rsbuild/index.ts, packages/rspeedy/core/src/index.ts, packages/rspeedy/core/test/cli/config.test.ts, packages/rspeedy/core/test/cli/fixtures/build-cache/build-dependencies.js, packages/rspeedy/core/test/cli/fixtures/build-cache/lynx.config.js, packages/rspeedy/core/test/config/performance.test-d.ts, packages/rspeedy/core/test/config/performance/buildCache.test.ts, packages/rspeedy/core/test/config/validate.test.ts
=> feat(rspeedy/core): add `performance.buildCache`

.github/workflows/test.yml, packages/rspeedy/core/etc/rspeedy.api.md
Prevent future regressions similar to #751.
=> test: check if `*.api.md` is up-to-date

packages/web-platform/web-tests/tests/react.spec.ts, packages/web-platform/web-tests/tests/react/basic-setstate-in-constructor/index.jsx, packages/web-platform/web-tests/tests/web-core.test.ts
https://app.codecov.io/gh/lynx-family/lynx-stack/tests/main?parameter=FLAKY_TESTS
* basic-setstate-in-constructor
* basic-setsate-with-cb
* api-sendGlobalEvent
* basic-element-x-input-focus
* basic-element-x-input-bindfocus
* basic-element-x-input-bindconfirm
=> chore: try to fix some flaky

packages/react/runtime/src/lifecycle/patch/isMainThreadHydrationFinished.ts, packages/react/runtime/src/lifecycle/patch/updateMainThread.ts, packages/react/runtime/src/lifecycle/reload.ts, packages/react/worklet-runtime/src/bindings/bindings.ts, packages/react/worklet-runtime/src/bindings/index.ts
implement main thread hydration tracking and update bindings
=> feat(react/runtime): implement main thread hydration tracking

packages/react/runtime/src/snapshot/ref.ts, packages/react/runtime/src/snapshot/workletRef.ts, packages/react/worklet-runtime/src/bindings/bindings.ts, packages/react/worklet-runtime/src/bindings/types.ts, packages/react/worklet-runtime/src/global.ts, packages/react/worklet-runtime/src/workletRuntime.ts
=> fix(react/runtime): fix some types of MTS

packages/react/runtime/src/snapshot/spread.ts, packages/react/runtime/src/snapshot/workletEvent.ts
=> fix(react/runtime): fix some types of MTS(2)

packages/react/runtime/__test__/snapshot/workletRef.test.jsx, packages/react/runtime/__test__/utils/envManager.ts, packages/react/runtime/__test__/worklet/workletRef.test.jsx, packages/react/runtime/src/worklet/workletRef.ts
Reset MainThreadRef id before each test case
=> test(react/runtime): reset MainThreadRef id before each test case

.changeset/chatty-bottles-tickle.md
Add the missing changeset for #801.
=> chore: add missing changeset

.github/workflows/deploy-main.yml, .github/workflows/nodejs-dependencies.yml, .github/workflows/rust.yml, .github/workflows/test.yml, .github/workflows/workflow-bench.yml, .github/workflows/workflow-build.yml, .github/workflows/workflow-test.yml, .github/workflows/workflow-website.yml
Set `persist-credentials: false` for `actions/checkout`.
Fix https://github.com/lynx-family/lynx-stack/security/code-scanning/88
See https://docs.zizmor.sh/audits/#artipacked for details.
=> ci: set `persist-credentials: false`

.changeset/forty-garlics-build.md, .changeset/old-rivers-drop.md, packages/webpack/css-extract-webpack-plugin/package.json, packages/webpack/react-refresh-webpack-plugin/package.json, packages/webpack/react-webpack-plugin/package.json, packages/webpack/template-webpack-plugin/etc/template-webpack-plugin.api.md, packages/webpack/template-webpack-plugin/src/LynxEncodePlugin.ts, packages/webpack/web-webpack-plugin/package.json
=> fix(webpack/template)!: remove unused `encodeBinary`

.changeset/lemon-clubs-beam.md
chore: update dependencies:
- @lynx-js/web-elements@0.7.2
- @lynx-js/web-core@0.13.2
=> chore(web): publish web-explorer

.github/workflows/nodejs-dependencies.yml, examples/react/package.json, pnpm-lock.yaml
Fix the [CI failure](https://github.com/lynx-family/lynx-stack/actions/runs/15203886593/job/42762783595?pr=899).
Also, added to merge_group to avoid future regression.
=> ci: fix multiple `@types/react` versions

.changeset/huge-donkeys-hope.md, packages/webpack/template-webpack-plugin/src/LynxTemplatePlugin.ts, packages/webpack/template-webpack-plugin/test/cases/hooks/before-emit-lepus/rspack.config.js, packages/webpack/template-webpack-plugin/test/cases/hooks/before-emit-lepus/webpack.config.js
=> fix: the lepus arg of beforeEmit hook to contain root chunk

eslint.config.js, packages/react/runtime/src/worklet/execMap.ts, packages/react/runtime/src/worklet/functionality.ts, packages/react/runtime/src/worklet/hmr.ts, packages/react/runtime/src/worklet/indexMap.ts
Try enabling eslint for `packages/react/runtime/src/worklet`
=> refactor(react/runtime): try enabling eslint for MTS

.changeset/green-rings-remain.md, pnpm-lock.yaml, pnpm-workspace.yaml
The internal CI is failing.
Reverts lynx-family/lynx-stack#939
=> Revert "chore(deps): update dependency @rsbuild/core to v1.3.22"

.changeset/forty-files-design.md, packages/rspeedy/plugin-react-alias/src/index.ts
Resolve runtime packages in parallel using `Promise.all`.
=> refactor(rspeedy/plugin-react-alias): resolve runtime packages in parallel using Promise.all

packages/rspeedy/upgrade-rspeedy/test/install.test.ts
Avoid snapshot mismatch on Windows.
issue: #81
=> test(upgrade-rspeedy): fix snapshot on Windows

.changeset/crazy-candies-design.md, packages/web-platform/web-constants/src/types/EventType.ts, packages/web-platform/web-mainthread-apis/src/createMainThreadGlobalThis.ts, packages/web-platform/web-mainthread-apis/src/utils/createCrossThreadEvent.ts, packages/web-platform/web-mainthread-apis/src/utils/createExposureService.ts, packages/web-platform/web-tests/tests/react.spec.ts, packages/web-platform/web-tests/tests/react/basic-event-target-id/index.jsx
=> fix: target.id is undefined

.changeset/dry-heads-happen.md, packages/react/runtime/src/snapshot.ts, packages/react/testing-library/src/__tests__/snapshot.test.jsx
=> fix(react): avoid memory leak when removing the child from page

packages/tools/vitest-setup/package.json, packages/webpack/css-extract-webpack-plugin/test/diagnostic/error/sass/expected/rspack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/compat/utf-8/expected/rspack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/jsx/component/expected/rspack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/jsx/component/expected/webpack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/jsx/namespace-name/expected/rspack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/jsx/namespace-name/expected/webpack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/module-build-failed/errors/expected/rspack.txt, packages/webpack/react-webpack-plugin/test/diagnostic/module-build-failed/errors/expected/webpack.txt, packages/webpack/test-tools/package.json, packages/webpack/test-tools/src/diagnostic.ts, pnpm-lock.yaml, pnpm-workspace.yaml
close https://github.com/lynx-family/lynx-stack/pull/1061
=> test: replace `file://` URL 

packages/rspeedy/plugin-react/test/lazy.test.ts
issue: #81
> [!NOTE]
> I think this would be the last one :)
=> test(rspeedy/react): fix lazy bundle build on Windows

.github/workflows/test.yml, packages/web-platform/web-tests/playwright.config.ts, packages/web-platform/web-tests/rspack.config.js, packages/web-platform/web-tests/shell-project/index.ts, packages/web-platform/web-tests/shell-project/web-core.ts, packages/web-platform/web-tests/tests/react.spec.ts, packages/web-platform/web-tests/tests/web-core.test.ts
[Feature]: Breaking Change: set the all-on-ui mode to be the default render #1080
=> ci: make the all-on-ui to be the default rendering mode

.gitattributes, .github/actions/setup-playwright/action.yml, .github/workflows/test.yml, .github/workflows/workflow-bench.yml, .github/workflows/workflow-test.yml, packages/rspeedy/plugin-react/test/basic.test.ts, packages/webpack/css-extract-webpack-plugin/test/diagnostic.test.ts
Enable Vitest on Windows CI.
close: #81
=> ci: enable vitest on Windows

packages/react/runtime/__test__/list.test.jsx, packages/react/runtime/__test__/snapshot/ref.test.jsx, packages/react/runtime/__test__/snapshotPatch.test.jsx, packages/react/runtime/src/backgroundSnapshot.ts, packages/react/runtime/src/hydrate.ts, packages/react/runtime/src/internal.ts, packages/react/runtime/src/lifecycle/patch/snapshotPatchApply.ts, packages/react/runtime/src/lifecycle/patch/updateMainThread.ts, packages/react/runtime/src/lifecycle/reload.ts, packages/react/runtime/src/list.ts, packages/react/runtime/src/listUpdateInfo.ts, packages/react/runtime/src/lynx/calledByNative.ts, packages/react/runtime/src/opcodes.ts, packages/react/runtime/src/pendingListUpdates.ts, packages/react/runtime/src/snapshot.ts, packages/react/runtime/src/snapshot/dynamicPartType.ts, packages/react/runtime/src/snapshot/list.ts, packages/react/runtime/src/snapshot/platformInfo.ts, packages/react/runtime/src/snapshot/spread.ts, packages/react/testing-library/src/__tests__/list.test.jsx
Ensures that there is no resolvable path back to this module via its dependencies.
=> fix(react/runtime): fix circular references between modules

.github/renovate.json5
=> chore(renovate): group linting and types

packages/react/runtime/src/lifecycle/patch/commit.ts, packages/react/runtime/src/lifecycle/patch/snapshotPatch.ts, packages/react/runtime/src/lifecycle/patch/updateMainThread.ts, packages/react/runtime/src/lynx/calledByNative.ts, packages/react/runtime/src/lynx/component.ts, packages/react/runtime/src/lynx/performance.ts, packages/react/runtime/src/lynx/tt.ts
=> refactor(react/runtime): try to reduce bundle size

.github/renovate.json5
Group `@prefresh/*` in Renovate.
close: #1184 
close: #1185
=> chore(renovate): group `@prefresh/*`

packages/react/worklet-runtime/__test__/workletRuntime.test.js, packages/react/worklet-runtime/src/workletRuntime.ts, packages/web-platform/web-tests/tests/react.spec.ts, packages/web-platform/web-tests/tests/react/basic-mts-mainthread-nested-ref/index.jsx
See the added test case.
close: m-6732315340
=> fix(react/worklet-runtime): should allow nested MTS ref

.github/workflows/test.yml
=> chore: improve ci
